Repository DFE-Digital/teaching-vacancies, pull requests merged in 2020-06, with the labels that each got.

#1510 Algolia instant search browser enhancements
  .eslintrc.json
  .github/workflows/test.yml
  app/controllers/api/coordinates_controller.rb
  app/frontend/packs/application.js
  app/frontend/packs/search.js
  app/frontend/src/googleTagManagerUrlSnippet.js
  app/frontend/src/lib/api.js
  app/frontend/src/lib/autocomplete.js
  app/frontend/src/lib/autocomplete.scss
  app/frontend/src/lib/autocomplete.test.js
  app/frontend/src/lib/autocomplete.view.js
  app/frontend/src/lib/utils.js
  app/frontend/src/lib/utils.test.js
  app/frontend/src/locationAutocomplete.js
  app/frontend/src/polyfill/URLSearchParams.polyfill.js
  app/frontend/src/polyfill/after.polyfill.js
  app/frontend/src/polyfill/classlist.polyfill.js
  app/frontend/src/polyfill/remove.polyfill.js
  app/frontend/src/search/client.js
  app/frontend/src/search/data/locations.js
  app/frontend/src/search/hits.js
  app/frontend/src/search/hits.test.js
  app/frontend/src/search/index.js
  app/frontend/src/search/query.js
  app/frontend/src/search/query.test.js
  app/frontend/src/search/ui/form.js
  app/frontend/src/search/ui/input.js
  app/frontend/src/search/ui/input.test.js
  app/frontend/src/search/ui/radius.js
  app/frontend/src/search/ui/sort.js
  app/frontend/src/search/ui/sort.test.js
  app/frontend/src/sortJobList.js
  app/frontend/styles/application.scss
  app/frontend/styles/components/location_finder.scss
  app/views/kaminari/_paginator.html.haml
  app/views/pages/home/_search.html.haml
  app/views/shared/_location_search_tag.html.haml
  app/views/vacancies/_filters.html.haml
  app/views/vacancies/_sorting_options.html.haml
  app/views/vacancies/_subscribe_link.html.haml
  app/views/vacancies/_vacancy.html.haml
  app/views/vacancies/index.html+phone.haml
  app/views/vacancies/index.html.haml
  config/locales/en.yml
  config/webpacker.yml
  documentation/ab-testing-with-google-optimize.md
  dump.rdb
  package.json
  spec/features/google_optimize_experiment_spec.rb
  spec/features/google_tag_manager_can_anonymise_page_url_spec.rb
  spec/features/job_seekers_can_search_for_vacancies_with_algolia_spec.rb
  yarn.lock
Labels: javascript

#1645 Remove Timecop and replace with Rails time helpers
  Gemfile
  Gemfile.lock
  spec/features/hiring_staff_receive_email_prompt_for_expired_vacancy_feedback_spec.rb
  spec/features/hiring_staff_session_timeout_spec.rb
  spec/features/job_seekers_can_apply_for_a_vacancy_spec.rb
  spec/features/job_seekers_can_manage_their_subscription.rb
  spec/features/job_seekers_can_unsubscribe_from_subscriptions_spec.rb
  spec/jobs/send_expired_vacancy_feedback_email_prompts_job_spec.rb
  spec/lib/dfe_sign_in_api_spec.rb
  spec/lib/performance_platform_sender_spec.rb
  spec/mailers/subscription_spec.rb
  spec/models/general_feedback_spec.rb
  spec/models/subscription_spec.rb
  spec/models/vacancy_publish_feedback_spec.rb
  spec/models/vacancy_spec.rb
  spec/services/authorisation_spec.rb
  spec/services/copy_vacancy_spec.rb
  spec/services/vacancy_algolia_alert_builder_spec.rb
  spec/services/vacancy_algolia_search_builder_spec.rb
  spec/support/shared_examples/counter.rb
  spec/support/time_helpers.rb
Labels: tech debt

#1644 Initial Dockerfile to be used for deploying to PaaS
  .dockerignore
  Dockerfile
  Makefile
  docker-compose.yml
  paas/web/manifest-docker.yml
Labels: DevOps

#1690 TEVA-882 job alert missing param
  app/frontend/src/search/index.js
  app/frontend/src/search/ui/alert.js
  app/frontend/src/search/ui/alert.test.js
  app/frontend/src/search/ui/hits.js
  app/frontend/src/search/ui/input/location.test.js
  app/frontend/src/search/ui/input/radius.js
  app/frontend/src/search/ui/input/radius.test.js
Labels: do not merge

#1700 initialise current location on domcontentloaded
  app/frontend/src/lib/currentLocation.js
Labels: bug, javascript

#1696 [TEVA-858] Deploy prometheus ecosystem
  .gitignore
  .terraform-version
  Gemfile
  Gemfile.lock
  Makefile
  bin/run-in-env
  terraform/app/README.md
  terraform/app/cloud-config/container-instance.yml.tpl
  terraform/app/container-definitions/google_api_rake_container_definition.json
  terraform/app/container-definitions/logspout_container_definition.json
  terraform/app/container-definitions/performance_platform_rake_container_definition.json
  terraform/app/container-definitions/rake_container_definition.json
  terraform/app/container-definitions/web_container_definition.json
  terraform/app/container-definitions/worker_container_definition.json
  terraform/app/lambda/lambda_cloudwatch_to_slack_opsgenie_payload.zip
  terraform/app/modules/cloudfront/cloudfront.tf
  terraform/app/modules/cloudfront/input.tf
  terraform/app/modules/cloudfront/output.tf
  terraform/app/modules/cloudwatch/cloudwatch.tf
  terraform/app/modules/cloudwatch/input.tf
  terraform/app/modules/cloudwatch/output.tf
  terraform/app/output.tf
  terraform/app/policies/cloudwatch-slack-lambda-policy.json
  terraform/app/policies/cloudwatch-slack-lambda-role.json
  terraform/app/policies/codebuild_policy.json
  terraform/app/policies/codebuild_role.json
  terraform/app/policies/codepipeline.json
  terraform/app/policies/codepipeline_role.json
  terraform/app/policies/ecs-autoscale-role-policy.json
  terraform/app/policies/ecs-autoscale-role.json
  terraform/app/policies/ecs-execution-role-policy.json
  terraform/app/policies/ecs-role.json
  terraform/app/policies/ecs-scheduled-task-policy.json
  terraform/app/policies/ecs-scheduled-task-role.json
  terraform/app/policies/ecs-service-role-policy.json
  terraform/app/policies/ecs-task-execution-role.json
  terraform/app/policies/sns-policy.json
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/monitoring/data.tf
  terraform/monitoring/files/alert.rules
  terraform/monitoring/files/alertmanager.yml
  terraform/monitoring/files/paas_dashboard.json
  terraform/monitoring/provider.tf
  terraform/monitoring/resources.tf
  terraform/monitoring/terraform.tf
  terraform/monitoring/variables.tf
  terraform/workspace-variables/workspace.tfvars.example
Labels: DevOps

#1704 deploy to dev & staging from docker image
  .dockerignore
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  Makefile
  docker-compose.deploy.yml
  docker-compose.yml
  dotenv.gpg
  paas/web/manifest-docker.yml
Labels: DevOps
