Repository DFE-Digital/teaching-vacancies, pull requests merged in 2021-11, with the labels that each got.

#4220 [TEVA-3368] split-prometheus-alert
  terraform/monitoring/config/alert.rules.yml
  terraform/monitoring/config/alert.test.yml
Labels: DevOps

#4219 [TEVA-3324] Optimise job role landing pages
  app/components/jobseekers/search_results/heading_component.rb
  app/views/vacancies/_title_and_description.html.slim
  app/views/vacancies/index.html.slim
  config/locales/en.yml
  config/locales/jobs.yml
  config/locales/landing_pages.yml
  config/routes.rb
  spec/components/jobseekers/search_results/heading_component_spec.rb
  spec/system/jobseekers_can_view_and_visit_homepage_facets_spec.rb
Labels: deploy

#4196 [TEVA-3328] Stream validation errors to BigQuery
  app/form_models/base_form.rb
  app/form_models/cookies_preferences_form.rb
  app/form_models/general_feedback_form.rb
  app/form_models/jobseekers/account_feedback_form.rb
  app/form_models/jobseekers/job_alert_further_feedback_form.rb
  app/form_models/jobseekers/job_application/base_form.rb
  app/form_models/jobseekers/sign_in_form.rb
  app/form_models/jobseekers/subscription_form.rb
  app/form_models/jobseekers/unsubscribe_feedback_form.rb
  app/form_models/publishers/job_listing/end_listing_form.rb
  app/form_models/publishers/job_listing/extend_deadline_form.rb
  app/form_models/publishers/job_listing/feedback_form.rb
  app/form_models/publishers/job_listing/vacancy_form.rb
  app/form_models/publishers/organisation_form.rb
  app/form_models/publishers/terms_and_conditions_form.rb
  app/form_models/publishers/vacancy_statistics_form.rb
  app/models/event_context.rb
  spec/form_models/base_form_spec.rb
Labels: deploy

#4231 [TEVA-3321] Update vacancy show page title
  app/helpers/vacancies_helper.rb
  app/views/layouts/application.html.slim
  app/views/vacancies/_show.html.slim
Labels: deploy

#4212 [TEVA-3319] Add Search form A:B test
  app/components/filters_component/filters_component.js
  app/components/panel_component.rb
  app/components/panel_component/panel_component.html.slim
  app/components/panel_component/panel_component.js
  app/components/panel_component/panel_component.scss
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/panel.scss
  app/views/vacancies/_search.html.slim
  config/ab_tests.yml
  spec/components/panel_component_spec.rb
Labels: deploy

#4211 [TEVA-3325] Trial update to breadcrumbs on teaching assistant jobs
  app/views/shared/vacancy/_jobseeker_view.html.slim
  config/locales/en.yml
Labels: deploy

#4221 [TEVA-3352] Vary the default search radius depending on location type
  app/components/jobseekers/search_results/heading_component.rb
  app/form_models/jobseekers/search_form.rb
  app/form_models/jobseekers/subscription_form.rb
  app/helpers/vacancies_options_helper.rb
  app/presenters/subscription_presenter.rb
  app/services/search/buffer_suggestions_builder.rb
  app/services/search/location_builder.rb
  app/services/search/radius_builder.rb
  app/services/search/radius_suggestions_builder.rb
  app/services/search/vacancy_search.rb
  app/views/shared/search/_radius.html.slim
  config/locales/en.yml
  config/locales/jobs.yml
  spec/components/jobseekers/search_results/heading_component_spec.rb
  spec/form_models/jobseekers/search_form_spec.rb
  spec/form_models/jobseekers/subscription_form_spec.rb
  spec/presenters/subscription_presenter_spec.rb
  spec/requests/subscriptions_spec.rb
  spec/services/search/buffer_suggestions_builder_spec.rb
  spec/services/search/location_builder_spec.rb
  spec/services/search/radius_builder_spec.rb
  spec/system/jobseekers_can_create_a_job_alert_from_a_search_spec.rb
  spec/system/jobseekers_can_search_from_home_page_spec.rb
Labels: deploy

#4232 [TEVA-3359] Update home page CTAs for hiring staff
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/footer.scss
  app/frontend/src/styles/application/signin.scss
  app/frontend/src/styles/base/_utilities.scss
  app/views/home/index.html.slim
  app/views/layouts/_footer.html.slim
  config/locales/en.yml
  spec/system/jobseekers_can_sign_in_to_their_account_spec.rb
  spec/system/publishers_can_sign_in_with_dfe_spec.rb
Labels: deploy

#4233 [TEVA-3371] filters to use new panel component
  app/components/filters_component.rb
  app/components/filters_component/filters_component.html.slim
  app/components/filters_component/filters_component.js
  app/components/filters_component/filters_component.scss
  app/components/panel_component.rb
  app/components/panel_component/panel_component.html.slim
  app/components/panel_component/panel_component.js
  app/components/panel_component/panel_component.scss
  app/frontend/src/styles/application/jobseekers/search-panel.scss
  app/views/shared/search/_location.html.slim
  app/views/vacancies/_search.html.slim
  config/locales/forms.yml
  spec/components/filters_component_spec.rb
  spec/components/panel_component_spec.rb
Labels: deploy

#4238 [TEVA-3033] Do not show error when no schools outside LA
  app/views/publishers/publisher_preferences/_form.html.slim
Labels: deploy

#4242 [TEVA-3405] introduce stimulus for new panel component
  .eslintrc.json
  app/components/panel_component.rb
  app/components/panel_component/panel.js
  app/components/panel_component/panel.scss
  app/components/panel_component/panel.test.js
  app/components/panel_component/panel_component.html.slim
  app/components/panel_component/panel_component.js
  app/components/panel_component/panel_component.scss
  app/frontend/packs/application.js
  app/frontend/src/application.js
  app/frontend/src/application/init.js
  app/frontend/src/application/jobseekers/__mocks__/location.js
  app/frontend/src/application/jobseekers/__mocks__/radius.js
  app/frontend/src/application/jobseekers/init.js
  app/frontend/src/application/publishers/init.js
  app/frontend/src/components/manageQualifications/manageQualifications.js
  app/frontend/src/components/manageQualifications/manageQualifications.test.js
  app/frontend/src/components/printPage/printPage.js
  app/frontend/src/components/printPage/printPage.scss
  app/frontend/src/components/printPage/printPage.test.js
  app/frontend/src/components/uploadDocuments/uploadDocuments.js
  app/frontend/src/components/uploadDocuments/uploadDocuments.scss
  app/frontend/src/components/utils.js
  app/frontend/src/styles/application.scss
  app/views/publishers/vacancies/job_applications/show.html.slim
  app/views/vacancies/_search.html.slim
  config/locales/forms.yml
  package.json
  spec/components/panel_component_spec.rb
  yarn.lock
Labels: deploy

#4247 [TEVA-3358] Remove expired job urls from Google index and sitemap
  app/controllers/sitemap_controller.rb
  app/jobs/remove_expired_vacancies_from_google_index_job.rb
  app/jobs/remove_vacancies_that_expired_yesterday_from_algolia_job.rb
  app/jobs/remove_vacancies_that_expired_yesterday_from_google_index_job.rb
  app/models/vacancy.rb
  app/views/shared/_meta.html.slim
  app/views/shared/vacancy/_jobseeker_view.html.slim
  app/views/vacancies/_key_dates_sidebar.html.slim
  app/views/vacancies/_show.html.slim
  config/locales/jobs.yml
  config/schedule.yml
  documentation/search.md
  lib/tasks/data.rake
  spec/jobs/remove_vacancies_that_expired_yesterday_from_algolia_job_spec.rb
  spec/jobs/remove_vacancies_that_expired_yesterday_from_google_index_job_spec.rb
  spec/sidekiq/sidekiq_spec.rb
  spec/system/application_seo_spec.rb
  spec/system/application_sitemap_spec.rb
Labels: deploy

#4266 [TEVA-3395] use gds bold style instead of strong HTML tag
  app/components/environment_banner_component/environment_banner_component.html.slim
  app/views/layouts/design_system.html.slim
  config/locales/en.yml
Labels: deploy

#4282 [URGENT] css selector for filters submit button fix
  app/components/filters_component/filters_component.scss
Labels: deploy

#4283 Force update of busybox version in container
  Dockerfile
Labels: deploy

#4274 Implement query parser for Postgres search
  Gemfile
  Gemfile.lock
  app/queries/vacancy_full_text_search_query.rb
  app/services/search/postgres/query_parser.rb
  app/services/search/postgres/query_transformer.rb
  config/initializers/search.rb
  config/search/oneway_synonyms.yml
  config/search/synonyms.yml
  spec/services/search/postgres/query_parser_spec.rb
  spec/services/search/postgres/query_transformer_spec.rb
Labels: deploy

#4277 [TEVA-3393] fix search results layout as per design
  app/components/card_component/card_component.scss
  app/components/jobseekers/vacancy_summary_component/vacancy_summary_component.html.slim
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/jobseekers/vacancies.scss
  app/frontend/src/styles/application/publishers/awaiting-feedback.scss
Labels: deploy

#4290 [TEVA-3469] Update Alpine packages
  Dockerfile
Labels: deploy

#4286 Update ruby gems
  Gemfile.lock
  app/components/publishers/vacancies_component.rb
  app/controllers/publishers/vacancies/build_controller.rb
  app/models/option.rb
  spec/lib/remove_invalid_subscriptions_spec.rb
Labels: deploy

#4276 [TEVA-3361] AB test alternative search results
  app/components/panel_component/panel.scss
  app/frontend/src/application/init.js
  app/frontend/src/components/autocomplete/autocomplete.js
  app/frontend/src/components/autocomplete/autocomplete.scss
  app/frontend/src/components/locationFinder/locationFinder.js
  app/frontend/src/styles/application/jobseekers/search-header.scss
  app/views/shared/search/_current_location.html.slim
  app/views/shared/search/_location.html.slim
  app/views/vacancies/_search.html.slim
  app/views/vacancies/index.html.slim
  config/ab_tests.yml
  spec/accessibility/search_experience_spec.rb
Labels: deploy

#4248 [TEVA-3406] WIP database outage
  Makefile
  README.md
  documentation/disaster-recovery.md
  terraform/app/modules/paas/main.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/dev.tfvars
Labels: DevOps, deploy

#4304 TEVA-3304 Job alert form tweaks
  app/components/filters_component/filters_component.html.slim
  app/components/filters_component/filters_component.scss
  app/frontend/src/styles/base/_utilities.scss
  app/views/shared/search/_radius.html.slim
  app/views/subscriptions/_fields.html.slim
  app/views/subscriptions/_form.html.slim
  app/views/subscriptions/edit.html.slim
  app/views/subscriptions/new.html.slim
  app/views/vacancies/_search.html.slim
  config/locales/en.yml
Labels: deploy

#4310 Update ruby gems
  Gemfile.lock
Labels: deploy

#4307 [TEVA-3449] Change jobseekers my applications tab
  app/views/jobseekers/job_applications/_job_application.html.slim
  app/views/jobseekers/job_applications/index.html.slim
  app/views/jobseekers/job_applications/review.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  spec/system/jobseekers_can_delete_a_draft_job_application_spec.rb
  spec/system/jobseekers_can_manage_their_job_applications_spec.rb
Labels: deploy

#4300 [TEVA-3441] convert autocomplete to stimulus component
  app/frontend/src/application.js
  app/frontend/src/application/init.js
  app/frontend/src/components/autocomplete/autocomplete.js
  app/frontend/src/components/autocomplete/autocomplete.scss
  app/views/shared/search/_location.html.slim
Labels: deploy

#4313 [TEVA-3445] Exclude universities from schools to manage in LA
  app/models/school.rb
  app/views/publishers/publisher_preferences/_form.html.slim
  spec/factories/schools.rb
  spec/system/publishers_can_filter_vacancies_in_their_dashboard_spec.rb
Labels: deploy

#4314 [TEVA-3450] Changes to job application review and show pages
  app/frontend/src/styles/application/applications.scss
  app/helpers/job_applications_helper.rb
  app/views/jobseekers/job_applications/_banner.html.slim
  app/views/jobseekers/job_applications/_job_application.html.slim
  app/views/jobseekers/job_applications/review.html.slim
  app/views/jobseekers/job_applications/show.html.slim
  app/views/publishers/vacancies/job_applications/show.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  spec/system/jobseekers_can_view_a_job_application_spec.rb
  spec/system/publishers_can_view_a_job_application_spec.rb
Labels: deploy

#4320 [TEVA-3426] Convert clipboard.js to stimulus component
  app/frontend/src/application.js
  app/frontend/src/application/init.js
  app/frontend/src/components/clipboard/clipboard.js
  app/frontend/src/components/clipboard/clipboard.test.js
  app/views/shared/vacancy/_copy_vacancy_link.html.slim
  config/locales/forms.yml
Labels: deploy

#4317 TEVA-3440 "manage qualifications" stimulus conversion
  .tool-versions
  app/frontend/src/application.js
  app/frontend/src/components/manageQualifications/manageQualifications.js
  app/frontend/src/components/manageQualifications/manageQualifications.test.js
  app/views/jobseekers/job_applications/qualifications/fields/_secondary_school.html.slim
Labels: deploy

#4326 [TEVA-3425] Convert uploadDocuments.js to stimulus component
  app/frontend/src/application.js
  app/frontend/src/application/init.js
  app/frontend/src/components/uploadDocuments/uploadDocuments.js
  app/helpers/documents_helper.rb
  app/views/publishers/vacancies/documents/_documents.html.slim
  app/views/publishers/vacancies/documents/show.html.slim
  app/views/publishers/vacancies/vacancy_form_partials/_submit.html.slim
Labels: deploy

#4330 add stimlulus polyfill package
  app/frontend/src/application.js
  package.json
  yarn.lock
Labels: deploy

#4337 Add AB test for new search
  app/controllers/vacancies_controller.rb
  config/ab_tests.yml
Labels: deploy

#4319 [TEVA-3305] Updates to Jobseeker Flows
  app/controllers/application_controller.rb
  app/controllers/jobseekers/sessions_controller.rb
  spec/accessibility/jobseekers_dashboard_experience_spec.rb
  spec/system/jobseekers_can_change_email_spec.rb
  spec/system/jobseekers_can_give_account_feedback_spec.rb
  spec/system/jobseekers_can_sign_in_to_their_account_spec.rb
  spec/system/jobseekers_can_sign_up_to_an_account_spec.rb
  spec/system/jobseekers_session_timeout_spec.rb
  spec/system/users_are_redirected_after_sign_in_spec.rb
  spec/system/users_can_only_be_signed_in_to_one_type_of_account_spec.rb
Labels: deploy

#4341 [TEVA-3424] Update locationFinder to use a stimulus controller
  app/components/flash_component/flash_component.js
  app/frontend/src/application.js
  app/frontend/src/application/init.js
  app/frontend/src/components/__mocks__/loader.js
  app/frontend/src/components/autocomplete/autocomplete.scss
  app/frontend/src/components/loader/loader.js
  app/frontend/src/components/loader/loader.scss
  app/frontend/src/components/locationFinder/locationFinder.js
  app/frontend/src/components/locationFinder/locationFinder.scss
  app/frontend/src/components/locationFinder/locationFinder.test.js
  app/frontend/src/lib/__mocks__/api.js
  app/frontend/src/lib/api.js
  app/frontend/src/lib/polyfill/after.polyfill.js
  app/frontend/src/lib/polyfill/remove.polyfill.js
  app/frontend/src/styles/application/jobseekers/search-panel.scss
  app/views/home/_search.html.slim
  app/views/shared/search/_current_location.html.slim
  app/views/shared/search/_location.html.slim
  app/views/shared/search/_radius.html.slim
  app/views/subscriptions/_fields.html.slim
  app/views/vacancies/_search.html.slim
Labels: deploy
