Repository DFE-Digital/teaching-vacancies, pull requests merged in 2021-07, with the labels that each got.

#3702 [TEVA-2758] Use github label for deployments of pull requests
  .github/workflows/build_and_deploy.yml
  .github/workflows/delete_review_app.yml
Labels: DevOps, deploy

#3693 docker security scan
  .github/workflows/build_and_deploy.yml
Labels: DevOps, deploy

#3708 Upgrade postgres from tier small-11 to small-12
  terraform/app/modules/paas/main.tf
  terraform/workspace-variables/staging.tfvars
Labels: DevOps

#3706 Add experiment for switching out search strategy
  app/controllers/vacancies_controller.rb
  app/services/search/strategies/experiment.rb
  app/services/search/strategies/pg_search.rb
  app/services/search/vacancy_search.rb
  spec/services/search/strategies/experiment_spec.rb
  spec/services/search/strategies/pg_search_spec.rb
  spec/support/search_helper.rb
Labels: deploy

#3707 Add radius to all location searches
  app/components/jobseekers/search_results/heading_component.rb
  app/frontend/src/application/jobseekers/init.js
  app/frontend/src/application/jobseekers/location.js
  app/frontend/src/application/jobseekers/location.test.js
  app/frontend/src/application/jobseekers/radius.js
  app/frontend/src/application/jobseekers/radius.test.js
  app/frontend/src/components/autocomplete/autocomplete.view.js
  app/frontend/src/components/locationFinder/locationFinder.js
  app/frontend/src/components/locationFinder/locationFinder.test.js
  app/helpers/vacancies_options_helper.rb
  app/services/search/location_builder.rb
  config/locales/jobs.yml
  spec/components/jobseekers/search_results/heading_component_spec.rb
  spec/services/search/location_builder_spec.rb
  spec/services/search/vacancy_search_spec.rb
Labels: deploy

#3697 [TEVA-2739] Update search input
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/jobseekers/keyword-search.scss
  app/frontend/src/styles/application/jobseekers/location-search.scss
  app/frontend/src/styles/application/jobseekers/search-panel.scss
  app/helpers/vacancies_options_helper.rb
  app/views/home/_filters.html.slim
  app/views/home/_search.html.slim
  app/views/shared/search/_current_location.html.slim
  app/views/shared/search/_keyword.html.slim
  app/views/shared/search/_location.html.slim
  app/views/shared/search/_radius.html.slim
  app/views/subscriptions/_fields.html.slim
  app/views/vacancies/_search.html.slim
  app/views/vacancies/index.html.slim
  config/locales/jobs.yml
  spec/system/jobseekers_can_create_a_job_alert_from_the_dashboard_spec.rb
  spec/system/jobseekers_can_search_from_home_page_spec.rb
Labels: deploy

#3714 [TEVA-2779] Sign in page for hiring staff and jobseeker users
  app/controllers/publishers/account_requests_controller.rb
  app/form_models/publishers/account_request_form.rb
  app/mailers/admins/account_mailer.rb
  app/models/account_request.rb
  app/views/admins/account_mailer/account_creation_request.text.erb
  app/views/jobseekers/registrations/new.html.slim
  app/views/jobseekers/sessions/new.html.slim
  app/views/layouts/application.html.slim
  app/views/pages/sign-in.html.slim
  app/views/publishers/account_requests/create.html.slim
  app/views/publishers/account_requests/new.html.slim
  app/views/publishers/login_keys/new.html.slim
  app/views/publishers/sessions/new.html.slim
  config/analytics.yml
  config/analytics_pii.yml
  config/initializers/notifications.rb
  config/locales/activerecord.yml
  config/locales/en.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  config/locales/mailers.yml
  config/locales/publishers.yml
  config/routes.rb
  db/migrate/20210708091608_create_account_requests.rb
  db/schema.rb
  spec/factories/account_requests.rb
  spec/form_models/publishers/account_request_form_spec.rb
  spec/mailers/admins/account_mailer_spec.rb
  spec/support/auth_helpers.rb
  spec/system/jobseekers_can_close_and_reactivate_account_spec.rb
  spec/system/jobseekers_can_sign_in_to_their_account_spec.rb
  spec/system/jobseekers_can_unlock_their_account_spec.rb
  spec/system/main_navigation_spec.rb
  spec/system/publishers_can_request_account_spec.rb
  spec/system/publishers_can_sign_in_by_email_spec.rb
  spec/system/publishers_can_sign_out_with_dfe_spec.rb
Labels: deploy

#3723 Reopen 3697 teva 2739 home page updates
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/jobseekers/keyword-search.scss
  app/frontend/src/styles/application/jobseekers/location-search.scss
  app/frontend/src/styles/application/jobseekers/search-panel.scss
  app/helpers/vacancies_options_helper.rb
  app/views/home/_filters.html.slim
  app/views/home/_search.html.slim
  app/views/shared/search/_current_location.html.slim
  app/views/shared/search/_keyword.html.slim
  app/views/shared/search/_location.html.slim
  app/views/shared/search/_radius.html.slim
  app/views/subscriptions/_fields.html.slim
  app/views/vacancies/_search.html.slim
  app/views/vacancies/index.html.slim
  config/locales/jobs.yml
  spec/smoke_tests/jobseekers_can_view_homepage_spec.rb
  spec/system/jobseekers_can_create_a_job_alert_from_the_dashboard_spec.rb
  spec/system/jobseekers_can_search_from_home_page_spec.rb
Labels: deploy

#3700 [TEVA-2740] rework of filters ui mainly to remove accordions
  app/components/filters_component/filters_component.html.slim
  app/components/filters_component/filters_component.js
  app/components/filters_component/filters_component.scss
  app/components/filters_component/filters_component.test.js
  app/form_models/jobseekers/search_form.rb
  app/form_models/jobseekers/subscription_form.rb
  app/frontend/images/svg/icon-close.svg
  app/frontend/src/components/form/form.js
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/icons.scss
  app/frontend/src/styles/application/jobseekers/filter-vacancies.scss
  app/views/subscriptions/_fields.html.slim
  app/views/vacancies/_search.html.slim
  app/views/vacancies/index.html.slim
  config/locales/forms.yml
  config/locales/jobs.yml
Labels: deploy

#3731 fix prod js filter errors
  app/components/filters_component/filters_component.js
Labels: deploy

#3732 Update to govuk-frontend 3.13.0
  package.json
  yarn.lock
Labels: deploy

#3736 Update govuk-link style
  app/frontend/packs/application.js
  app/frontend/src/styles/application.scss
Labels: deploy

#3717 [TEVA-2720] Validate job applications before submitting them
  app/components/review_component/review_component.scss
  app/controllers/application_controller.rb
  app/controllers/jobseekers/job_applications_controller.rb
  app/controllers/publishers/vacancies/base_controller.rb
  app/controllers/publishers/vacancies/publish_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/form_models/jobseekers/job_application/review_form.rb
  app/helpers/job_application_helper.rb
  app/models/job_application.rb
  app/views/jobseekers/job_applications/review.html.slim
  app/views/jobseekers/job_applications/review/_declarations.html.slim
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
  app/views/jobseekers/job_applications/review/_equal_opportunities.html.slim
  app/views/jobseekers/job_applications/review/_personal_details.html.slim
  app/views/jobseekers/job_applications/review/_personal_statement.html.slim
  app/views/jobseekers/job_applications/review/_professional_status.html.slim
  app/views/publishers/vacancies/_error_tag.html.slim
  app/views/publishers/vacancies/edit.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_applying_for_the_job.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_important_dates.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_job_details.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_job_location.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_job_summary.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_pay_package.html.slim
  app/views/publishers/vacancies/review.html.slim
  app/views/shared/_error_messages.html.slim
  config/locales/activerecord.yml
  config/locales/notifications.yml
  spec/helpers/job_application_helper_spec.rb
  spec/system/jobseekers_can_submit_a_job_application_spec.rb
  spec/system/publishers_can_edit_a_published_vacancy_as_a_school_spec.rb
Labels: deploy

#3726 Update documentation
  documentation/aws-roles-and-cli-tools.md
  documentation/deployments.md
  documentation/docker.md
Labels: DevOps

#3739 [TEVA-2841] Increase default search radius to 10
  app/views/shared/search/_radius.html.slim
  app/views/vacancies/_key_dates_sidebar.html.slim
  spec/system/jobseekers_can_search_from_home_page_spec.rb
  spec/system/jobseekers_can_view_a_vacancy_spec.rb
Labels: deploy

#3744 [TEVA-2632] Add A/B test for contents tabs on job listings
  app/views/shared/vacancy/_jobseeker_view.html.slim
  config/ab_tests.yml
Labels: deploy

#3713 [TEVA-2389] new copy to clip board functionality
  app/frontend/src/application/init.js
  app/frontend/src/components/clipboard/clipboard.js
  app/frontend/src/components/clipboard/clipboard.test.js
  app/views/publishers/vacancies/_show.html.slim
  app/views/publishers/vacancies/summary.html.slim
  app/views/shared/vacancy/_copy_vacancy_link.html.slim
  app/views/shared/vacancy/_jobseeker_view.html.slim
  app/views/shared/vacancy/_share_buttons.html.slim
  package.json
  spec/system/publishers_can_share_their_vacancy_spec.rb
  yarn.lock
Labels: deploy

#3743 Upgrade to Ruby 3.0.2 and Bundler 2.2.22
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: deploy

#3733 Update bundler config
  Dockerfile
Labels: DevOps, deploy

#3724 [TEVA-2732] Show job page
  app/components/banner_component/banner_component.scss
  app/components/card_component.rb
  app/components/card_component/card_component.html.slim
  app/components/card_component/card_component.scss
  app/components/dashboard_component.rb
  app/components/dashboard_component/dashboard_component.html.slim
  app/components/dashboard_component/dashboard_component.scss
  app/components/filters_component/filters_component.js
  app/components/publishers/vacancies_component.rb
  app/components/publishers/vacancies_component/vacancies_component.html.slim
  app/controllers/publishers/vacancies_controller.rb
  app/frontend/src/styles/application/govuk-notification-banner.scss
  app/frontend/src/styles/application/publishers/publisher.scss
  app/helpers/job_application_helper.rb
  app/models/vacancy.rb
  app/views/jobseekers/dashboard/_account_header.html.slim
  app/views/publishers/vacancies/job_applications/_banner.html.slim
  app/views/publishers/vacancies/job_applications/index.html.slim
  app/views/publishers/vacancies/show.html.slim
  config/locales/forms.yml
  config/locales/jobs.yml
  config/locales/publishers.yml
  spec/components/card_component_spec.rb
  spec/components/dashboard_component_spec.rb
  spec/components/publishers/vacancies_component_spec.rb
  spec/helpers/job_application_helper_spec.rb
  spec/system/publishers_can_copy_a_vacancy_spec.rb
  spec/system/publishers_can_delete_vacancies_spec.rb
  spec/system/publishers_can_edit_a_draft_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_end_a_job_listing_early_spec.rb
  spec/system/publishers_can_extend_a_deadline_spec.rb
  spec/system/publishers_can_manage_job_applications_for_a_vacancy_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_save_and_return_later_spec.rb
  spec/system/publishers_can_view_vacancies_spec.rb
Labels: deploy

#3746 Persist radius selection to following page
  app/controllers/home_controller.rb
  app/controllers/subscriptions_controller.rb
  app/controllers/vacancies_controller.rb
  app/form_models/jobseekers/search_form.rb
  app/form_models/jobseekers/subscription_form.rb
  app/views/home/_search.html.slim
  app/views/shared/search/_radius.html.slim
  app/views/subscriptions/_fields.html.slim
  app/views/subscriptions/edit.html.slim
  app/views/subscriptions/new.html.slim
  app/views/vacancies/_search.html.slim
  app/views/vacancies/_sorting_options.html.slim
  spec/controllers/subscriptions_controller_spec.rb
  spec/form_models/jobseekers/search_form_spec.rb
  spec/form_models/jobseekers/subscription_form_spec.rb
  spec/system/jobseekers_can_create_a_job_alert_from_a_search_spec.rb
  spec/system/jobseekers_can_search_from_home_page_spec.rb
Labels: deploy

#3763 [TEVA-2860] Dac report initial A11y fixes
  app/components/card_component/card_component.scss
  app/components/detail_component/detail_component.html.slim
  app/components/detail_component/detail_component.scss
  app/components/filters_component/filters_component.html.slim
  app/components/review_component.rb
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/publishers/publisher.scss
  app/helpers/vacancies_helper.rb
  app/views/jobseekers/job_applications/build/ask_for_support.html.slim
  app/views/jobseekers/job_applications/build/declarations.html.slim
  app/views/jobseekers/job_applications/build/employment_history.html.slim
  app/views/jobseekers/job_applications/build/equal_opportunities.html.slim
  app/views/jobseekers/job_applications/build/personal_details.html.slim
  app/views/jobseekers/job_applications/build/personal_statement.html.slim
  app/views/jobseekers/job_applications/build/professional_status.html.slim
  app/views/jobseekers/job_applications/build/qualifications.html.slim
  app/views/jobseekers/job_applications/build/references.html.slim
  app/views/jobseekers/job_applications/index.html.slim
  app/views/jobseekers/job_applications/review.html.slim
  app/views/jobseekers/registrations/new.html.slim
  app/views/jobseekers/sessions/new.html.slim
  app/views/layouts/application.html.slim
  app/views/pages/job-application-preview.html.slim
  app/views/pages/privacy-policy.html.slim
  app/views/pages/terms-and-conditions.html.slim
  app/views/publishers/sessions/new.html.slim
  app/views/publishers/vacancies/build/job_location.html.slim
  app/views/publishers/vacancies/documents/_documents.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_supporting_documents.html.slim
  app/views/publishers/vacancies/job_applications/index.html.slim
  app/views/publishers/vacancies/show.html.slim
  app/views/publishers/vacancies/summary.html.slim
  app/views/shared/job_application/_show.html.slim
  app/views/shared/search/_location.html.slim
  app/views/shared/vacancy/_copy_vacancy_link.html.slim
  app/views/vacancies/index.html.slim
  config/locales/forms.yml
  spec/components/detail_component_spec.rb
  spec/components/review_component_spec.rb
  spec/support/vacancy_helpers.rb
Labels: deploy

#3758 [TEVA-2604] Display page when attempting to view a withdrawn application
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/views/publishers/vacancies/job_applications/withdrawn.html.slim
  config/locales/publishers.yml
  config/routes.rb
  spec/requests/publishers/vacancies/job_applications_spec.rb
Labels: deploy

#3757 [TEVA-2862] do not allow radius select to auto submit form
  app/frontend/src/components/form/form.js
  app/frontend/src/components/form/form.test.js
  app/views/shared/search/_radius.html.slim
Labels: deploy

#3772 Truncate about_school field when indexing
  app/models/concerns/indexable.rb
Labels: deploy

#3766 Content update to blue box on homepage
  config/locales/en.yml
Labels: deploy

#3753 Alert on slow http response
  documentation/alert-runbook.md
  terraform/monitoring/config/alert.rules.yml
  terraform/monitoring/config/alert.test.yml
Labels: DevOps

#3777 [TEVA-2885] Adapt behavior of navbar component
  app/components/navbar_component.rb
  app/helpers/link_helper.rb
Labels: deploy

#3775 Create _Improvements_to_the_hiring_staff_dashboard_2021_07_22.html.erb
  app/views/updates/update_files/_Improvements_to_the_hiring_staff_dashboard_2021_07_22.html.erb
Labels: deploy

#3780 Create _Updates_to_search_2021_07_23.html.erb
  app/views/updates/update_files/_Updates_to_search_2021_07_23.html.erb
Labels: deploy

#3788 [TEVA-2921] Move COMMIT_SHA to bottom of Dockerfile
  Dockerfile
Labels: DevOps, deploy

#3791 [TEVA-2908] add visually hidden prefix to footer links
  app/views/home/_vacancy_facets.html.slim
  config/locales/en.yml
Labels: deploy

#3785 [TEVA-2568] Automatically highlight gaps in employment
  app/components/review_component/review_component.scss
  app/controllers/concerns/jobseekers/wizardable.rb
  app/controllers/jobseekers/job_applications/breaks_controller.rb
  app/controllers/jobseekers/job_applications/build_controller.rb
  app/controllers/jobseekers/job_applications/employments_controller.rb
  app/controllers/jobseekers/job_applications_controller.rb
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/form_models/jobseekers/job_application/details/break_form.rb
  app/form_models/jobseekers/job_application/employment_history_form.rb
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/applications.scss
  app/helpers/job_application_helper.rb
  app/models/employment.rb
  app/views/jobseekers/job_applications/breaks/_fields.html.slim
  app/views/jobseekers/job_applications/breaks/confirm_destroy.html.slim
  app/views/jobseekers/job_applications/breaks/edit.html.slim
  app/views/jobseekers/job_applications/breaks/new.html.slim
  app/views/jobseekers/job_applications/build/employment_history.html.slim
  app/views/jobseekers/job_applications/build/qualifications.html.slim
  app/views/jobseekers/job_applications/build/references.html.slim
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
  app/views/shared/job_application/_explained_employment_break.html.slim
  app/views/shared/job_application/_show.html.slim
  app/views/shared/job_application/_unexplained_employment_break.html.slim
  config/analytics.yml
  config/locales/activerecord.yml
  config/locales/en.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  config/routes.rb
  db/migrate/20210721145619_add_employment_type_to_employments.rb
  db/schema.rb
  spec/factories/job_applications.rb
  spec/form_models/jobseekers/job_application/employment_history_form_spec.rb
  spec/services/jobseekers/job_applications/quick_apply_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers_can_add_employments_to_their_job_application_spec.rb
  spec/system/jobseekers_can_complete_a_job_application_spec.rb
  spec/system/jobseekers_can_review_a_job_application_spec.rb
Labels: deploy

#3792 fix Readonly Role to view sanitised backup
  terraform/common/iam.tf
Labels: DevOps

#3793 add extra text for scheduled job heading
  app/views/publishers/vacancies/job_applications/_banner.html.slim
  config/locales/publishers.yml
Labels: deploy

#3795 [TEVA-2742] Show statistics tab on vacancy page
  app/components/detail_component/detail_component.html.slim
  app/components/detail_component/detail_component.scss
  app/controllers/publishers/vacancies/statistics_controller.rb
  app/models/vacancy.rb
  app/services/publishers/vacancy_stats.rb
  app/views/publishers/vacancies/job_applications/_banner.html.slim
  app/views/publishers/vacancies/statistics/show.html.slim
  config/locales/publishers.yml
  config/routes.rb
  spec/models/vacancy_spec.rb
  spec/services/publishers/vacancy_stats_spec.rb
  spec/system/publishers_can_view_vacancy_statistics_spec.rb
Labels: deploy
