Repository DFE-Digital/teaching-vacancies, pull requests merged in 2021-08, with the labels that each got.

#3808 Convert bullet point symbols in job listing details to li tags
  app/presenters/vacancy_presenter.rb
  spec/presenters/vacancy_presenter_spec.rb
Labels: deploy

#3796 Use Snyk docker image scanner
  .github/workflows/build_and_deploy.yml
  Dockerfile
Labels: DevOps, deploy

#3813 [TEVA- 2960] replace with current autocomplete with alphagov accessible version
  app/frontend/src/application/jobseekers/init.js
  app/frontend/src/components/autocomplete/autocomplete.js
  app/frontend/src/components/autocomplete/autocomplete.scss
  app/frontend/src/components/autocomplete/autocomplete.test.js
  app/frontend/src/components/autocomplete/autocomplete.view.js
  app/frontend/src/components/loader/loader.js
  app/frontend/src/components/loader/loader.scss
  app/frontend/src/components/locationFinder/locationFinder.js
  app/frontend/src/lib/api.js
  app/views/home/_search.html.slim
  app/views/shared/search/_current_location.html.slim
  app/views/shared/search/_keyword.html.slim
  app/views/shared/search/_location.html.slim
  app/views/shared/search/_radius.html.slim
  app/views/vacancies/_search.html.slim
  package.json
  yarn.lock
Labels: deploy

#3820 [TEVA-2981] Fix bug caused by nil expires_at
  app/views/publishers/vacancies/job_applications/_banner.html.slim
  config/locales/publishers.yml
  spec/system/publishers_can_save_and_return_later_spec.rb
Labels: deploy

#3823 fix location finder bug due to new autocomplete
  app/frontend/src/components/locationFinder/locationFinder.js
  app/frontend/src/components/locationFinder/locationFinder.scss
  app/frontend/src/components/locationFinder/locationFinder.test.js
Labels: deploy

#3810 Use make file in continuous integration
  .github/workflows/build_and_deploy.yml
  .github/workflows/deploy_app.yml
  Makefile
  terraform/app/terraform.tf
  terraform/app/variables.tf
Labels: deploy

#3828 teva-2990 use orig form input name for automcmplete form input
  app/frontend/src/components/autocomplete/autocomplete.js
Labels: deploy

#3821 Migrate Vacancy.completed_step to an array (migration step 1)
  app/controllers/concerns/publishers/wizardable.rb
  app/controllers/publishers/vacancies/copy_controller.rb
  app/controllers/publishers/vacancies/documents_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/form_models/publishers/job_listing/important_dates_form.rb
  app/form_models/publishers/job_listing/job_location_form.rb
  app/form_models/publishers/job_listing/vacancy_form.rb
  app/helpers/vacancies_helper.rb
  app/views/publishers/vacancies/build/_steps.html.slim
  config/analytics.yml
  db/migrate/20210804155509_add_completed_steps_to_vacancy.rb
  db/schema.rb
  lib/tasks/data.rake
  spec/factories/vacancies.rb
Labels: deploy

#3830 Don't show '0 applicants' when applications disabled
  app/components/publishers/vacancies_component/vacancies_component.html.slim
Labels: deploy

#3825 Drop Vacancy.completed_step column (migration step 2)
  app/controllers/concerns/publishers/wizardable.rb
  app/controllers/publishers/vacancies/base_controller.rb
  app/controllers/publishers/vacancies/documents_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/form_models/publishers/job_listing/copy_vacancy_form.rb
  app/form_models/publishers/job_listing/important_dates_form.rb
  app/form_models/publishers/job_listing/job_location_form.rb
  app/form_models/publishers/job_listing/vacancy_form.rb
  app/helpers/vacancies_helper.rb
  config/analytics.yml
  db/migrate/20210806161056_drop_vacancy_completed_step.rb
  db/schema.rb
  lib/tasks/data.rake
  spec/factories/vacancies.rb
Labels: deploy

#3829 [TEVA-2991] Include 'how to apply' in the review step
  app/components/publishers/vacancy_form_page_heading_component.rb
  app/helpers/vacancies_helper.rb
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_applying_for_the_job.html.slim
  spec/support/vacancy_helpers.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_local_authority_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
Labels: deploy

#3803 [TEVA-2751] Add column encryption with Lockbox: step A
  Gemfile
  Gemfile.lock
  app/jobs/send_feedback_to_big_query_job.rb
  app/models/application_record.rb
  app/models/employment.rb
  app/models/event_context.rb
  app/models/job_application.rb
  app/models/jobseeker.rb
  app/models/publisher.rb
  app/models/qualification.rb
  app/models/reference.rb
  config/environments/test.rb
  db/migrate/20210721135549_add_lockbox_ciphertext_columns.rb
  db/schema.rb
  lib/tasks/data.rake
  spec/factories/feedbacks.rb
  spec/models/application_record_spec.rb
  spec/models/event_context_spec.rb
  spec/rails_helper.rb
  spec/services/copy_vacancy_spec.rb
  spec/spec_helper.rb
Labels: deploy

#3804 [TEVA-2751] Add column encryption with Lockbox: step B
  app/models/employment.rb
  app/models/job_application.rb
  app/models/jobseeker.rb
  app/models/publisher.rb
  app/models/qualification.rb
  app/models/reference.rb
Labels: deploy

#3805 [TEVA-2751] Add column encryption with Lockbox: step C
  README.md
  app/jobs/send_feedback_to_big_query_job.rb
  app/models/job_application.rb
  db/migrate/20210722094927_drop_unencrypted_columns.rb
  db/schema.rb
  db/scripts/sanitise.sql
Labels: deploy

#3806 [TEVA-2751] Add column encryption with Lockbox: step D
  app/models/employment.rb
  app/models/job_application.rb
  app/models/jobseeker.rb
  app/models/publisher.rb
  app/models/qualification.rb
  app/models/reference.rb
Labels: deploy

#3842 [TEVA-3011] Update terraform cloudfoundry provider
  .github/workflows/build_and_deploy.yml
  terraform/app/versions.tf
  terraform/monitoring/versions.tf
Labels: DevOps

#3844 [TEVA-2965] Update "Pay package" page on vacancies
  .rubocop.yml
  app/components/jobseekers/vacancy_details_component/vacancy_details_component.html.slim
  app/components/jobseekers/vacancy_summary_component/vacancy_summary_component.html.slim
  app/controllers/concerns/publishers/wizardable.rb
  app/form_models/publishers/job_listing/pay_package_form.rb
  app/views/publishers/vacancies/build/pay_package.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_pay_package.html.slim
  config/analytics.yml
  config/locales/forms.yml
  config/locales/jobs.yml
  db/migrate/20210811152359_add_actual_salary_to_vacancies.rb
  db/schema.rb
  spec/components/jobseekers/vacancy_details_component_spec.rb
  spec/components/jobseekers/vacancy_summary_component_spec.rb
  spec/factories/vacancies.rb
  spec/support/vacancy_helpers.rb
  spec/system/publishers_can_edit_a_published_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_save_and_return_later_spec.rb
Labels: deploy

#3847 [Teva 2124] Create research app
  .github/workflows/build_and_deploy.yml
  Makefile
  terraform/workspace-variables/research.tfvars
  terraform/workspace-variables/research_app_env.yml
Labels: DevOps

#3851 Fix NQT suitable bugs (option 1)
  app/models/vacancy.rb
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_job_details.html.slim
Labels: deploy

#3856 Update and add new keys to research_app_env.yml
  terraform/workspace-variables/research.tfvars
  terraform/workspace-variables/research_app_env.yml
Labels: DevOps

#3857 [TEVA-2961] remove optional from pusedo content on form labels as not accessible
  app/frontend/packs/application.js
  app/frontend/src/application/publishers/init.js
  app/frontend/src/application/publishers/textareaFormat.js
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/application/form.scss
  app/frontend/src/styles/base/_utilities.scss
  app/helpers/organisation_helper.rb
  app/views/jobseekers/account_feedbacks/new.html.slim
  app/views/jobseekers/job_applications/build/personal_details.html.slim
  app/views/jobseekers/job_applications/build/professional_status.html.slim
  app/views/jobseekers/job_applications/employments/_fields.html.slim
  app/views/jobseekers/job_applications/qualifications/fields/_other.html.slim
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
  app/views/jobseekers/job_applications/review/_personal_details.html.slim
  app/views/jobseekers/job_applications/submit.html.slim
  app/views/publishers/account_requests/new.html.slim
  app/views/publishers/vacancies/build/applying_for_the_job.html.slim
  app/views/publishers/vacancies/build/important_dates.html.slim
  app/views/publishers/vacancies/build/job_details.html.slim
  app/views/publishers/vacancies/build/job_summary.html.slim
  app/views/publishers/vacancies/build/pay_package.html.slim
  app/views/publishers/vacancies/copy/new.html.slim
  app/views/publishers/vacancies/extend_deadline/show.html.slim
  app/views/publishers/vacancies/job_applications/reject.html.slim
  app/views/publishers/vacancies/job_applications/shortlist.html.slim
  app/views/publishers/vacancies/summary.html.slim
  config/locales/forms.yml
  config/locales/jobs.yml
Labels: deploy

#3863 [TEVA-3024] improve accessibilty markup for footer links
  app/views/home/_vacancy_facets.html.slim
  config/locales/en.yml
  spec/system/jobseekers_can_view_and_visit_homepage_facets_spec.rb
Labels: deploy

#3822 [TEVA-2880] Seed QA with accurate dummy data
  db/seeds.rb
  spec/factories/vacancies.rb
  spec/mailers/publishers/feedback_prompt_mailer_spec.rb
  spec/system/application_sitemap_spec.rb
  spec/system/jobseekers_can_manage_their_job_applications_spec.rb
  spec/system/publishers_can_add_stats_to_a_vacancy_spec.rb
  spec/system/publishers_can_filter_vacancies_in_their_dashboard_spec.rb
Labels: deploy

#3865 [TEVA-2971] ensure filters panel container is not focusable on desktop screen size
  app/components/filters_component/filters_component.js
Labels: deploy

#3871 [TEVA-3033] Add slack notification on docker scan failure.
  .github/workflows/build_and_deploy.yml
Labels: DevOps

#3850 upgrade to postgres 12
  terraform/workspace-variables/production.tfvars
Labels: DevOps

#3879 Update terms-and-conditions.html.slim
  app/views/pages/terms-and-conditions.html.slim
Labels: deploy

#3885 Update slack notification message
  .github/workflows/build_and_deploy.yml
Labels: deploy

#3887 [TEVA-3007] fix missing notification count in main nav
  app/components/navbar_component.rb
  app/components/navbar_component/navbar_component.scss
  app/views/layouts/application.html.slim
  config/locales/en.yml
  spec/components/navbar_component_spec.rb
  spec/system/main_navigation_spec.rb
  spec/system/publishers_can_view_their_notifications_spec.rb
Labels: deploy

#3886 [TEVA-2871] Job roles changes in job listing journey
  app/components/jobseekers/vacancy_details_component/vacancy_details_component.html.slim
  app/controllers/concerns/publishers/wizardable.rb
  app/controllers/publishers/vacancies/base_controller.rb
  app/controllers/publishers/vacancies/build_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/form_models/jobseekers/search_form.rb
  app/form_models/jobseekers/subscription_form.rb
  app/form_models/publishers/job_listing/job_details_form.rb
  app/form_models/publishers/job_listing/job_role_details_form.rb
  app/form_models/publishers/job_listing/job_role_form.rb
  app/helpers/vacancies_helper.rb
  app/models/vacancy.rb
  app/presenters/vacancy_presenter.rb
  app/views/publishers/vacancies/build/job_details.html.slim
  app/views/publishers/vacancies/build/job_location.html.slim
  app/views/publishers/vacancies/build/job_role.html.slim
  app/views/publishers/vacancies/build/job_role_details.html.slim
  app/views/publishers/vacancies/edit.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_job_details.html.slim
  app/views/publishers/vacancies/edit_vacancy_sections/_edit_job_role.html.slim
  app/views/publishers/vacancies/review.html.slim
  app/views/publishers/vacancies/show.html.slim
  app/views/publishers/vacancies/vacancy_form_partials/_save_and_return_submit.html.slim
  app/views/vacancies/_search.html.slim
  config/locales/activerecord.yml
  config/locales/forms.yml
  config/locales/jobs.yml
  config/locales/publishers.yml
  spec/components/jobseekers/vacancy_details_component_spec.rb
  spec/factories/vacancies.rb
  spec/form_models/publishers/job_listing/job_details_form_spec.rb
  spec/services/search/criteria_deviser_spec.rb
  spec/services/search/filters_builder_spec.rb
  spec/support/vacancy_helpers.rb
  spec/system/application_sitemap_spec.rb
  spec/system/publishers_can_edit_a_draft_vacancy_as_a_school_group_spec.rb
  spec/system/publishers_can_edit_a_draft_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_edit_a_published_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_preview_a_vacancy_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_local_authority_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
  spec/system/publishers_can_save_and_return_later_spec.rb
  spec/system/publishers_session_timeout_spec.rb
Labels: deploy

#3896 [TEVA-2873] add changes to apply form for education support role
  app/views/publishers/vacancies/build/applying_for_the_job.html.slim
  config/locales/publishers.yml
  spec/support/vacancy_helpers.rb
Labels: deploy
