Repository DFE-Digital/teaching-vacancies, pull requests merged in 2022-09, with the labels that each got.

#5354 Update Terraform StatusCake provider to 2.0.3
  .gitignore
  .tool-versions
  terraform/app/modules/statuscake/main.tf
  terraform/app/modules/statuscake/variables.tf
  terraform/app/modules/statuscake/versions.tf
  terraform/app/terraform.tf
  terraform/app/versions.tf
  terraform/workspace-variables/production.tfvars.json
Labels: deploy, devops

#5382 Upgrade Terraform to version 1.2.8
  .devcontainer/Dockerfile
  .github/actions/deploy/action.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/delete_review_app.yml
  .gitignore
  .tool-versions
  documentation/deployments.md
  terraform/app/.terraform.lock.hcl
  terraform/app/versions.tf
  terraform/common/.terraform.lock.hcl
  terraform/common/versions.tf
  terraform/monitoring/.terraform.lock.hcl
  terraform/monitoring/versions.tf
Labels: deploy, devops

#5403 Update gems
  Gemfile
  Gemfile.lock
Labels: deploy

#5424 [TEVA-4303] update hint for finding jobseeker TRN
  app/views/jobseekers/job_applications/build/personal_details.html.slim
  config/locales/forms.yml
Labels: deploy

#5433 Review fe tweaks
  app/assets/stylesheets/base/_global.scss
  app/assets/stylesheets/base/_utilities.scss
  app/helpers/vacancies_helper.rb
  app/views/publishers/vacancies/review_banners/_closed.html.slim
  app/views/publishers/vacancies/review_banners/_complete_draft.html.slim
  app/views/publishers/vacancies/review_banners/_incomplete_draft.html.slim
  app/views/publishers/vacancies/review_banners/_published.html.slim
  app/views/publishers/vacancies/review_banners/_scheduled.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_pay_package.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_working_patterns.html.slim
  app/views/vacancies/search/_results.html.slim
  spec/helpers/vacancies_helper_spec.rb
Labels: deploy

#5435 [TEVA-4436] Update copy job listing process
  app/components/dashboard_component/dashboard_component.html.slim
  app/controllers/publishers/vacancies/copy_controller.rb
  app/form_models/publishers/job_listing/copy_vacancy_form.rb
  app/helpers/vacancies_helper.rb
  app/services/copy_vacancy.rb
  app/views/publishers/vacancies/copy/new.html.slim
  config/routes.rb
  spec/form_models/publishers/job_listing/copy_vacancy_form_spec.rb
  spec/helpers/vacancies_helper_spec.rb
  spec/system/publishers_can_copy_a_vacancy_spec.rb
Labels: deploy

#5447 [683] Fix dependabot for terraform
  .github/dependabot.yml
Labels: devops

#5450 [683] Use lowercase devops label
  .github/dependabot.yml
Labels: devops

#5395 [TEVA-4390] update job listing create journey application choice page
  app/assets/stylesheets/components/review.scss
  app/components/job_application_review_component/section.rb
  app/components/review_component.rb
  app/components/review_component/review_component.html.slim
  app/controllers/publishers/vacancies/build_controller.rb
  app/helpers/qualifications_helper.rb
  app/views/jobseekers/job_applications/_explained_employment_break.html.slim
  app/views/jobseekers/job_applications/_unexplained_employment_break.html.slim
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
  app/views/jobseekers/job_applications/review/_personal_statement.html.slim
  app/views/jobseekers/job_applications/review/_qualifications.html.slim
  app/views/jobseekers/job_applications/review/_references.html.slim
  app/views/publishers/vacancies/build/applying_for_the_job.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  config/locales/publishers.yml
  spec/components/job_application_review_component_spec.rb
  spec/factories/job_applications.rb
  spec/factories/qualifications.rb
  spec/factories/references.rb
  spec/helpers/qualifications_helper_spec.rb
Labels: deploy
