Repository DFE-Digital/teaching-vacancies, pull requests merged in 2022-04, with the labels that each got.

#4875 Remove breadcrumbs from search results page
  app/views/vacancies/index.html.slim
Labels: deploy

#4869 [TEVA-4001] Remove redirected location pages from sitemap
  app/controllers/sitemap_controller.rb
  config/data/redirected_location_landing_pages.yml
  spec/system/application_sitemap_spec.rb
Labels: deploy

#4880 [TEVA-4077] Edit school hiring advice links
  app/helpers/links_helper.rb
  app/helpers/organisations_helper.rb
  app/views/layouts/_footer.html.slim
  app/views/layouts/_header.html.slim
  app/views/publishers/new_features/reminder.html.slim
  app/views/publishers/vacancies/build/applying_for_the_job.html.slim
  config/locales/en.yml
  config/locales/publishers.yml
  spec/system/publishers_are_reminded_of_application_functionality_spec.rb
Labels: deploy

#4867 add full screen plugin for leaflet maps
  app/components/map_component/map.js
  app/components/map_component/map.scss
  app/frontend/packs/application.js
  package.json
  yarn.lock
Labels: deploy

#4885 [TEVA-3914] Tidy supportal DSI config
  .env.development
  config/initializers/omniauth.rb
  config/routes.rb
  documentation/dsi-integration.md
  terraform/workspace-variables/dev_app_env.yml
  terraform/workspace-variables/local_app_env.yml
  terraform/workspace-variables/production_app_env.yml
  terraform/workspace-variables/qa_app_env.yml
  terraform/workspace-variables/staging_app_env.yml
Labels: deploy

#4834 [TEVA-3869] Supportal feedback management
  .github/workflows/test.yml
  app/components/supportal_table_component.rb
  app/components/supportal_table_component/supportal_table_component.html.slim
  app/components/supportal_table_component/supportal_table_component.scss
  app/controllers/support_users/feedbacks_controller.rb
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/base/_grid.scss
  app/frontend/src/styles/layouts/support-users/feedbacks.scss
  app/helpers/components_helper.rb
  app/models/feedback.rb
  app/models/feedback_reporting_period.rb
  app/views/layouts/application.html.slim
  app/views/support_users/dashboard/dashboard.html.slim
  app/views/support_users/feedbacks/_feedback_table.html.slim
  app/views/support_users/feedbacks/_job_alerts_feedback_table.html.slim
  app/views/support_users/feedbacks/_reporting_period_control.html.slim
  app/views/support_users/feedbacks/_tables.html.slim
  app/views/support_users/feedbacks/_tabs.html.slim
  app/views/support_users/feedbacks/general.html.slim
  app/views/support_users/feedbacks/job_alerts.html.slim
  app/views/support_users/feedbacks/satisfaction_ratings.html.slim
  config/application.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220322100704_fix_feedback_string_search_criteria.rb
  db/migrate/20220322142612_add_category_to_feedback.rb
  db/schema.rb
  spec/components/supportal_table_component_spec.rb
  spec/models/feedback_reporting_period_spec.rb
  spec/system/support_users/dfe_sign_in_spec.rb
  spec/system/support_users/dfe_sign_out_spec.rb
  spec/system/support_users/feedback_spec.rb
Labels: do not merge, deploy

#4894 Travel time poc ideas
  app/components/map_component.rb
  app/components/map_component/map.js
  app/components/map_component/map.scss
  app/components/map_component/map_component.html.slim
  app/frontend/packs/application.js
  app/services/search/vacancy_search.rb
  package.json
  yarn.lock
Labels: deploy

#4915 Abstract map_component
  app/components/map_component.rb
  app/components/map_component/map.js
  app/components/map_component/map.test.js
  app/components/map_component/map_component.html.slim
  app/helpers/maps_helper.rb
  app/views/vacancies/listing/_organisation_details.html.slim
  app/views/vacancies/search/_results.html.slim
  spec/components/map_component_spec.rb
Labels: deploy

#4933 Fix supportal page width and select styling
  app/frontend/src/styles/application.scss
  app/frontend/src/styles/base/_grid.scss
  app/frontend/src/styles/layouts/support_users/feedbacks.scss
  app/views/layouts/application.html.slim
  app/views/support_users/feedbacks/_feedback_table.html.slim
  app/views/support_users/feedbacks/_job_alerts_feedback_table.html.slim
  app/views/support_users/feedbacks/_reporting_period_control.html.slim
  app/views/support_users/feedbacks/general.html.slim
  app/views/support_users/feedbacks/job_alerts.html.slim
  app/views/support_users/feedbacks/satisfaction_ratings.html.slim
Labels: deploy

#4935 Create how-to-approve-access-for-hiring-staff.md
  app/views/content/get-help-hiring/how-to-approve-access-for-hiring-staff.md
Labels: deploy

#4942 Devops label on dependabot PRs
  .github/dependabot.yml
Labels: DevOps

#4943 [TEVA-4099] Disable new features page
  app/controllers/publishers/organisations_controller.rb
  spec/system/publishers_are_reminded_of_application_functionality_spec.rb
  spec/system/publishers_are_shown_new_features_page_spec.rb
Labels: deploy

#4948 [TEVA-3994] Command to edit application secrets
  Makefile
  documentation/application-secrets.md
Labels: DevOps

#4955 [TEVA-4145] Remove similar jobs ab test
  app/frontend/src/styles/layouts/vacancies/show.scss
  app/views/vacancies/_show.html.slim
  app/views/vacancies/listing/_similar_jobs.html.slim
  config/ab_tests.yml
Labels: deploy

#4946 Change supportal feedback tables
  app/components/supportal_table_component.rb
  app/controllers/concerns/support_users/satisfaction_rating_types.rb
  app/controllers/support_users/feedbacks_controller.rb
  app/frontend/src/styles/layouts/support_users/feedbacks.scss
  app/models/feedback.rb
  app/views/support_users/feedbacks/_feedback_table.html.slim
  app/views/support_users/feedbacks/general.html.slim
  app/views/support_users/feedbacks/job_alerts.html.slim
  app/views/support_users/feedbacks/satisfaction_ratings.html.slim
  config/locales/en.yml
  spec/system/support_users/feedback_spec.rb
Labels: deploy

#4950 Small tweaks on long form articles
  app/views/content/get-help-hiring/how-to-approve-access-for-hiring-staff.md
  app/views/content/get-help-hiring/how-to-request-organisation-access.md
Labels: deploy

#4971 Update accepting-job-applications-on-teaching-vacancies.md
  app/views/content/get-help-hiring/accepting-job-applications-on-teaching-vacancies.md
Labels: deploy
