Repository DFE-Digital/teaching-vacancies, pull requests merged in 2022-11, with the labels that each got.

#5517 Add Fusion vacancy source
  .env.test
  app/jobs/import_from_vacancy_sources_job.rb
  app/vacancy_sources/fusion_vacancy_source.rb
  app/vacancy_sources/united_learning_vacancy_source.rb
  spec/fixtures/files/vacancy_sources/fusion.json
  spec/vacancy_sources/fusion_vacancy_source_spec.rb
Labels: deploy

#5549 Increase the character count to 300 for school_offer, skills_and_experience and further_details sections of the vacancy creation process
  app/assets/javascript/components/editor/editor.js
  app/form_models/publishers/job_listing/about_the_role_form.rb
  app/views/publishers/vacancies/build/about_the_role.html.slim
  config/locales/activerecord.yml
  spec/factories/vacancies.rb
  spec/form_models/publishers/job_listing/about_the_role_form_spec.rb
Labels: deploy

#5551 TEVA-4481: Remove links to schools/trusts from the job listings page
  app/helpers/vacancies_helper.rb
  spec/helpers/vacancies_helper_spec.rb
  spec/system/jobseekers_can_view_organisation_landing_pages_spec.rb
Labels: deploy

#5552 Only show change location link when is a trust
  app/views/publishers/vacancies/vacancy_review_sections/_job_details.html.slim
Labels: deploy

#5547 Add DfE Analytics gem
  .env.test
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/location_polygon.rb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/initializers/dfe_analytics.rb
  spec/jobs/alert_mailer_job_spec.rb
  spec/rails_helper.rb
  spec/system/dfe_analytics_spec.rb
Labels: deploy

#5542 Teva 4405 create the school profile page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/link_list.scss
  app/helpers/organisations_helper.rb
  app/views/layouts/_header.html.slim
  app/views/publishers/schools/_organisation.html.slim
  app/views/publishers/schools/index.html.slim
  app/views/publishers/schools/show.html.slim
  config/locales/en.yml
  config/locales/publishers.yml
  spec/system/publishers_can_manage_settings_spec.rb
Labels: deploy

#5555 Stop using set-output in workflow
  .github/actions/prepare-app-env/action.yml
Labels: deploy, devops, github-actions

#5560 Merge index and show actions and pages and rename schools controller
  app/controllers/publishers/organisations_controller.rb
  app/views/layouts/_header.html.slim
  app/views/publishers/organisations/_organisation.html.slim
  app/views/publishers/organisations/edit.html.slim
  app/views/publishers/organisations/show.html.slim
  app/views/publishers/schools/index.html.slim
  app/views/publishers/schools/show.html.slim
  config/locales/publishers.yml
  config/routes.rb
  spec/system/publishers_can_manage_settings_spec.rb
Labels: deploy

#5582 Replace 'School hiring guides' with 'Hiring guides'
  app/views/layouts/_footer.html.slim
  app/views/layouts/_header.html.slim
  config/locales/en.yml
Labels: deploy

#5544 [TEVA-4408] Create the "Schools" page
  app/controllers/schools_controller.rb
  app/form_models/school_search_form.rb
  app/models/organisation.rb
  app/models/school.rb
  app/models/school_group.rb
  app/queries/organisation_location_query.rb
  app/services/search/school_search.rb
  app/views/schools/index.html.slim
  app/views/schools/search/_form.html.slim
  app/views/schools/search/_results.html.slim
  app/views/schools/search/_stats.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/services/search/school_search_spec.rb
Labels: deploy

#5581 [TEVA-4472] Update vacancies index search fields and heading
  app/assets/stylesheets/layouts/vacancies/index.scss
  app/components/search_results_heading_component.rb
  app/components/search_results_heading_component/search_results_heading_component.html.slim
  app/helpers/components_helper.rb
  app/views/vacancies/index.html.slim
  app/views/vacancies/search/_fields_and_button.html.slim
  app/views/vacancies/search/_location.html.slim
  app/views/vacancies/search/_page_title_and_description.html.slim
  config/locales/jobs.yml
  spec/components/search_results_heading_component_spec.rb
  spec/system/jobseekers_can_view_landing_pages_spec.rb
  spec/system/jobseekers_can_view_organisation_landing_pages_spec.rb
Labels: deploy

#5583 add error class to editor component when form builder error
  app/assets/javascript/components/editor/editor.js
  app/assets/javascript/components/editor/editor.test.js
  app/assets/stylesheets/components/editor.scss
Labels: deploy

#5584 Displaying profile incomplete banners
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/base/govuk/components/_inset-text.scss
  app/assets/stylesheets/components/link_list.scss
  app/helpers/organisations_helper.rb
  app/models/organisation.rb
  app/models/school_group.rb
  app/views/publishers/organisations/_organisation.html.slim
  app/views/publishers/organisations/show.html.slim
  config/environments/development.rb
  config/locales/publishers.yml
Labels: deploy

#5585 [TEVA-4548] Update search results layout
  app/assets/stylesheets/layouts/vacancies/index.scss
  app/views/schools/index.html.slim
  app/views/vacancies/search/_filters.html.slim
  app/views/vacancies/search/_results.html.slim
  spec/system/jobseekers_can_search_for_jobs_spec.rb
  spec/system/jobseekers_can_view_all_the_jobs_spec.rb
Labels: deploy

#5586 Fix issue allowing no application form for published job
  app/controllers/publishers/vacancies/application_forms_controller.rb
  app/form_models/publishers/job_listing/application_form_form.rb
  app/helpers/documents_helper.rb
  app/views/publishers/vacancies/build/application_form.html.slim
  spec/requests/publishers/vacancies/application_forms_spec.rb
  spec/system/publishers_can_edit_a_published_vacancy_as_a_school_spec.rb
Labels: deploy

#5587 Displayed work history in chronological order and fix breaks in work history
  app/views/jobseekers/job_applications/_unexplained_employment_break.html.slim
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
Labels: deploy

#5603 [TEVA-4534] Fix subscription job roles translation path
  app/presenters/subscription_presenter.rb
Labels: deploy

#5605 Update error messages on 'About the role' page
  app/form_models/publishers/job_listing/about_the_role_form.rb
  config/locales/activerecord.yml
  spec/form_models/publishers/job_listing/about_the_role_form_spec.rb
Labels: deploy

#5602 [TEVA-4485] Add text overflow styling to govuk-panel
  app/assets/stylesheets/base/_global.scss
Labels: deploy

#5604 Update sidekiq
  Gemfile
  Gemfile.lock
Labels: deploy

#5619 Added school filters
  app/controllers/organisations_controller.rb
  app/form_models/school_search_form.rb
  app/models/organisation.rb
  app/models/school.rb
  app/services/search/school_search.rb
  app/views/organisations/index.html.slim
  app/views/organisations/search/_filters.html.slim
  app/views/organisations/search/_form.html.slim
  config/locales/organisations.yml
  spec/services/search/school_search_spec.rb
Labels: deploy

#5595 [TEVA-4486] add secondary jobseeker navigation
  app/assets/stylesheets/components/tabs.scss
  app/assets/stylesheets/layouts/_header.scss
  app/assets/stylesheets/layouts/home/index.scss
  app/components/tabs_component/tabs_component.html.slim
  app/views/jobseekers/sessions/new.html.slim
  app/views/layouts/_sub_navigation.html.slim
  app/views/layouts/application.html.slim
  app/views/organisations/index.html.slim
  app/views/organisations/schools/index.html.slim
  app/views/organisations/search/_filters.html.slim
  app/views/organisations/show.html.slim
  app/views/pages/sign-in.html.slim
  app/views/publishers/organisations/preview.html.slim
  app/views/publishers/organisations/schools/preview.html.slim
  app/views/publishers/sessions/new.html.slim
  config/locales/jobseekers.yml
  config/locales/organisations.yml
  spec/components/tabs_component_spec.rb
  spec/system/jobseekers_can_close_and_reactivate_account_spec.rb
  spec/system/jobseekers_can_sign_in_to_their_account_spec.rb
  spec/system/jobseekers_can_sign_out_from_their_account_spec.rb
  spec/system/jobseekers_can_unlock_their_account_spec.rb
  spec/system/jobseekers_can_view_all_the_jobs_spec.rb
  spec/system/jobseekers_can_view_an_organisation_spec.rb
  spec/system/jobseekers_can_view_their_dashboard_spec.rb
  spec/system/main_navigation_spec.rb
  spec/system/publishers_can_preview_a_profile_spec.rb
  spec/system/publishers_can_sign_in_by_email_spec.rb
  spec/system/publishers_can_sign_in_with_dfe_spec.rb
  spec/system/publishers_can_sign_out_with_dfe_spec.rb
  spec/system/publishers_can_visit_the_public_listings_spec.rb
  spec/system/publishers_have_to_accept_terms_spec.rb
  spec/system/support_users/dfe_sign_out_spec.rb
Labels: deploy

#5627 Dont show closed schools on the schools index page
  app/controllers/organisations_controller.rb
Labels: deploy

#5623 Update gems
  Gemfile.lock
Labels: do not merge, deploy

#5629 Update paper_trail gem
  Gemfile.lock
Labels: deploy

#5630 Update rack-protection gem
  Gemfile.lock
Labels: deploy
