Repository DFE-Digital/teaching-vacancies, pull requests merged in 2023-11, with the labels that each got.

#6514 [743] Backup Azure database daily
  .github/workflows/backup_production_db.yml
  .github/workflows/database-copy.yml
  .github/workflows/dump_db.yml
  .github/workflows/restore-paas-db-to-aks.yml
  .github/workflows/restore_db.yml
  bin/dump-db
  bin/restore-db
  documentation/database-backups.md
Labels: devops

#6515 Patch vulnerability in Docker image libx11 version
  Dockerfile
Labels: deploy

#6504 Set landing page for account confirmation
  app/controllers/jobseekers/confirmations_controller.rb
  app/controllers/jobseekers/unlocks_controller.rb
  app/models/jobseeker.rb
  app/views/jobseekers/confirmations/already_confirmed.html.slim
  config/locales/jobseekers.yml
  spec/models/jobseeker_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers_can_sign_up_to_an_account_spec.rb
  spec/system/jobseekers_can_unlock_their_account_spec.rb
Labels: deploy

#6520 Patch Imagemagic vulnerable version in Dockerfile
  Dockerfile
Labels: deploy

#6519 Replace "Invite to Apply" journey with enabling direct email contact to candidates
  README.md
  app/assets/javascript/js_components/clipboard/clipboard.js
  app/assets/javascript/js_components/trackedLink/trackedLink.js
  app/controllers/publishers/invitations_controller.rb
  app/form_models/publishers/invite_form.rb
  app/helpers/links_helper.rb
  app/mailers/publishers/invitations_mailer.rb
  app/models/invitation_to_apply.rb
  app/views/publishers/invitations/index.html.slim
  app/views/publishers/invitations/jobs.html.slim
  app/views/publishers/invitations/review.html.slim
  app/views/publishers/invitations_mailer/invite_to_apply.text.erb
  app/views/publishers/jobseeker_profiles/_layout.html.slim
  config/analytics.yml
  config/analytics_custom_events.yml
  config/analytics_pii.yml
  config/locales/mailers.yml
  config/locales/publishers.yml
  config/locales/publishers/invite.yml
  config/routes.rb
  db/migrate/20231109165747_remove_invitation_to_applies_fks.rb
  db/migrate/20231109165757_drop_invitation_to_applies.rb
  db/schema.rb
  documentation/front-end.md
  spec/system/publishers/publishers_can_contact_jobseekers_from_their_profile_spec.rb
  spec/system/publishers/publishers_can_invite_jobseekers_to_apply_for_vacancies_from_their_profile_spec.rb
Labels: deploy, javascript, ruby

#6523 Remove "dev" and "sandbox" from Codebase
  .github/workflows/build_and_deploy.yml
  Makefile
  app/assets/stylesheets/components/environment_banner.scss
  app/components/environment_banner_component/environment_banner_component.html.slim
  app/helpers/application_helper.rb
  app/mailers/application_mailer.rb
  app/views/layouts/_footer.html.slim
  app/views/layouts/_phase_banner.html.slim
  app/views/pages/sandbox.html.slim
  config/initializers/notifications.rb
  documentation/application-secrets.md
  documentation/continuous-delivery.md
  documentation/terraform.md
  spec/helpers/application_helper_spec.rb
  spec/mailers/jobseekers/alert_mailer_spec.rb
  spec/mailers/jobseekers/job_application_mailer_spec.rb
  spec/mailers/jobseekers/subscription_mailer_spec.rb
  spec/mailers/publishers/authentication_fallback_mailer_spec.rb
  spec/mailers/publishers/expired_vacancy_feedback_prompt_mailer_spec.rb
  spec/mailers/publishers/job_application_mailer_spec.rb
Labels: deploy

#6524 [713] Postgres server maintenance schedule
  terraform/app/modules/paas/aks_database.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/production.tfvars.json
Labels: devops

#6528 Fix Docker image vulnerability on PostgreSQL client
  Dockerfile
Labels: deploy

#6530 Fix Job Application seeds
  db/seeds.rb
Labels: bug

#6529 changed server image and switched to container
  documentation/deployments.md
  terraform/app/modules/paas/aks_database.tf
  terraform/workspace-variables/review.tfvars.json
Labels: deploy

#6526 Fix resend email confirmation link
  app/controllers/jobseekers/confirmations_controller.rb
  app/controllers/jobseekers/registrations_controller.rb
  app/views/jobseekers/confirmations/_new_hidden_email.html.slim
  app/views/jobseekers/confirmations/_new_with_email.html.slim
  app/views/jobseekers/confirmations/new.html.slim
  app/views/layouts/_head_meta.html.slim
  config/locales/jobseekers.yml
  spec/system/jobseekers_can_sign_up_to_an_account_spec.rb
Labels: bug, deploy, ruby

#6532 Fix typo in govuk components method call
  app/views/publishers/vacancies/vacancy_review_sections/_application_process.html.slim
Labels: bug

#6536 Align test/devcontainer PG version with Production
  .devcontainer/docker-compose.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: devops
