Repository DFE-Digital/teaching-vacancies, pull requests merged in 2023-09, with the labels that each got.

#6337 Fix vulnerable Alpine procps-ng version
  Dockerfile
Labels: deploy

#5799 Enable Every sync
  app/jobs/import_from_vacancy_sources_job.rb
  app/vacancy_sources/vacancy_source/source/every.rb
  spec/fixtures/files/vacancy_sources/every.json
  spec/vacancy_sources/vacancy_source/source/every_spec.rb
Labels: deploy

#6343 Redis deployment
  Makefile
  terraform/aks/.terraform.lock.hcl
  terraform/aks/cluster_data.tf
  terraform/aks/config/review.tfvars.json
  terraform/aks/config/review_Terrafile
  terraform/aks/database.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/app/modules/paas/aks_redis.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
Labels: deploy, devops

#6348 Visa application migration
  app/vacancy_sources/vacancy_source/source/every.rb
  app/vacancy_sources/vacancy_source/source/fusion.rb
  app/vacancy_sources/vacancy_source/source/my_new_term.rb
  app/vacancy_sources/vacancy_source/source/united_learning.rb
  app/vacancy_sources/vacancy_source/source/ventrus.rb
  config/analytics.yml
  db/migrate/20230907153216_add_visa_sponsorship_available_to_vacancies.rb
  db/schema.rb
  lib/tasks/update_visa_sponsorship_available.rake
  spec/jobs/import_from_vacancy_sources_job_spec.rb
  spec/vacancy_sources/vacancy_source/source/every_spec.rb
  spec/vacancy_sources/vacancy_source/source/fusion_spec.rb
  spec/vacancy_sources/vacancy_source/source/my_new_term_spec.rb
  spec/vacancy_sources/vacancy_source/source/united_learning_spec.rb
  spec/vacancy_sources/vacancy_source/source/ventrus_spec.rb
Labels: deploy

#6352 [530] Deploy web application to AKS
  .github/workflows/build_and_deploy.yml
  Makefile
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/aks_database.tf
  terraform/app/modules/paas/aks_redis.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/app/versions.tf
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/production_app_env.yml
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/qa_app_env.yml
  terraform/workspace-variables/review.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/sandbox_app_env.yml
  terraform/workspace-variables/staging.tfvars.json
  terraform/workspace-variables/staging_app_env.yml
Labels: deploy, devops

#6353 [530] Fix Azure database name suffix issue
  terraform/app/modules/paas/variables.tf
Labels: devops

#6328 Distance sorting
  app/form_models/jobseekers/search_form.rb
  app/queries/location_query.rb
  app/services/search/vacancy_search.rb
  app/services/search/vacancy_sort.rb
  app/views/vacancies/index.html.slim
  app/views/vacancies/search/_sort.html.slim
  config/brakeman.ignore
  config/locales/jobs.yml
  spec/queries/vacancy_location_query_spec.rb
  spec/services/search/radius_builder_spec.rb
  spec/services/search/vacancy_search_spec.rb
  spec/services/search/vacancy_sort_spec.rb
  spec/system/jobseekers_can_search_for_jobs_spec.rb
Labels: deploy

#6360 Add worker application
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/dev.tfvars.json
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/review.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: deploy

#6362 Remove status cake
  terraform/app/terraform.tf
  terraform/workspace-variables/production.tfvars.json
Labels: deploy, devops

#6336 Rephrase the right to work questions
  app/views/jobseekers/job_applications/build/personal_details.html.slim
  app/views/jobseekers/profiles/personal_details/work.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  spec/system/jobseekers_can_manage_a_profile_spec.rb
Labels: deploy

#6371 Bugfix: Allow legacy roles in vacancy search filter queries
  app/queries/vacancy_filter_query.rb
  spec/queries/vacancy_filter_query_spec.rb
Labels: bug, deploy

#6374 Fix distance sorting
  app/form_models/jobseekers/search_form.rb
  app/queries/location_query.rb
  app/queries/vacancy_full_text_search_query.rb
  app/services/search/vacancy_search.rb
  app/services/search/vacancy_sort.rb
  app/views/vacancies/index.html.slim
  app/views/vacancies/search/_sort.html.slim
  config/brakeman.ignore
  config/locales/jobs.yml
  spec/queries/vacancy_location_query_spec.rb
  spec/services/search/radius_builder_spec.rb
  spec/services/search/vacancy_search_spec.rb
  spec/services/search/vacancy_sort_spec.rb
  spec/system/jobseekers_can_search_for_jobs_spec.rb
Labels: deploy

#6351 Add visa sponsorship question to job listing wizard
  app/controllers/concerns/publishers/wizardable.rb
  app/controllers/publishers/vacancies/build_controller.rb
  app/form_models/publishers/job_listing/visa_sponsorship_form.rb
  app/services/publishers/vacancies/vacancy_step_process.rb
  app/views/publishers/vacancies/build/visa_sponsorship.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_application_process.html.slim
  config/locales/forms.yml
  config/locales/jobs.yml
  config/locales/publishers.yml
  spec/factories/vacancies.rb
  spec/support/vacancy_helpers.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_local_authority_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
Labels: deploy

#6379 Replace CF-dependant command for app start
  Dockerfile
  documentation/docker.md
  documentation/terraform.md
  lib/tasks/cloudfoundry.rake
  lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake
  terraform/app/variables.tf
  terraform/workspace-variables/review.tfvars.json
Labels: deploy

#6383 Upgrade libwebp to compatible version
  Dockerfile
Labels: deploy

#6386 [264] Remove extra inputs from the refresh DB workflow
  .github/workflows/restore-paas-db-to-aks.yml
Labels: devops

#6387 [264] Fix refresh DB workflow environment
  .github/workflows/restore-paas-db-to-aks.yml
Labels: devops

#6267 Add broadbean integration vacancy source
  .env.development
  .env.test
  app/jobs/import_from_vacancy_sources_job.rb
  app/vacancy_sources/vacancy_source/source/broadbean.rb
  spec/fixtures/files/vacancy_sources/broadbean.xml
  spec/vacancy_sources/vacancy_source/source/broadbean_spec.rb
Labels: deploy

#6380 Show visa sponsorship status on job listing
  app/views/vacancies/listing/_job_details.html.slim
  app/views/vacancies/search/_results.html.slim
  config/locales/en.yml
  config/locales/jobs.yml
  spec/support/vacancy_helpers.rb
Labels: deploy

#6397 Profile location update
  app/views/jobseekers/profiles/_summary.html.slim
  app/views/publishers/jobseeker_profiles/index.html.slim
  spec/factories/jobseeker_profiles.rb
  spec/system/publishers/publishers_can_view_a_jobseeker_profile_spec.rb
Labels: deploy

#6409 Add AKS credentials command to makefile
  Makefile
Labels: deploy

#6413 Add cloudfront AKS configuration
  terraform/app/modules/cloudfront/variables.tf
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/production_app_env.yml
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/qa_app_env.yml
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/sandbox_app_env.yml
  terraform/workspace-variables/staging.tfvars.json
  terraform/workspace-variables/staging_app_env.yml
Labels: devops

#6414 Fix: Do not override vacancy source parsing errors
  app/jobs/import_from_vacancy_sources_job.rb
  spec/jobs/import_from_vacancy_sources_job_spec.rb
  spec/vacancy_sources/vacancy_source/source/broadbean_spec.rb
Labels: bug

#6408 Change copy on key stages page of jobseeker profile form
  app/form_models/jobseekers/job_preferences_form.rb
  config/locales/forms.yml
  spec/system/jobseekers_can_manage_a_profile_spec.rb
Labels: deploy

#6416 Fix phase mapping for all sources
  app/vacancy_sources/vacancy_source/source/broadbean.rb
  app/vacancy_sources/vacancy_source/source/every.rb
  app/vacancy_sources/vacancy_source/source/fusion.rb
  app/vacancy_sources/vacancy_source/source/my_new_term.rb
  app/vacancy_sources/vacancy_source/source/united_learning.rb
  app/vacancy_sources/vacancy_source/source/ventrus.rb
  spec/fixtures/files/vacancy_sources/united_learning.xml
  spec/vacancy_sources/vacancy_source/source/broadbean_spec.rb
  spec/vacancy_sources/vacancy_source/source/every_spec.rb
  spec/vacancy_sources/vacancy_source/source/fusion_spec.rb
  spec/vacancy_sources/vacancy_source/source/my_new_term_spec.rb
  spec/vacancy_sources/vacancy_source/source/united_learning_spec.rb
  spec/vacancy_sources/vacancy_source/source/ventrus_spec.rb
Labels: bug

#6418 Fix United Learning organisation mapping
  app/vacancy_sources/vacancy_source/source/united_learning.rb
  spec/vacancy_sources/vacancy_source/source/united_learning_spec.rb
Labels: bug

#6417 [606] Configure DFE Sign-in redirect URL for AKS environments
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
  terraform/workspace-variables/production_app_env.yml
  terraform/workspace-variables/qa_app_env.yml
  terraform/workspace-variables/sandbox_app_env.yml
  terraform/workspace-variables/staging_app_env.yml
Labels: devops

#6427 [606] Disable DFE sign in for review apps
  terraform/app/.terraform.lock.hcl
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
Labels: devops

#6428 Fix legacy working patterns for United Learning
  app/vacancy_sources/vacancy_source/source/united_learning.rb
  spec/vacancy_sources/vacancy_source/source/united_learning_spec.rb
Labels: bug

#6401 Profile location update mats
  app/views/publishers/jobseeker_profiles/index.html.slim
  config/locales/publishers.yml
  spec/system/publishers/publishers_can_search_for_jobseeker_profiles_spec.rb
Labels: deploy

#6426 Show preferred subjects on jobseeker profiles
  app/models/job_preferences.rb
  app/views/jobseekers/profiles/_summary.html.slim
  app/views/publishers/jobseeker_profiles/search/_results.html.slim
  config/locales/jobseekers.yml
  config/locales/publishers.yml
  spec/system/publishers/publishers_can_search_for_jobseeker_profiles_spec.rb
  spec/system/publishers/publishers_can_view_a_jobseeker_profile_spec.rb
Labels: deploy

#6435 Prod db env fix
  .github/workflows/restore-paas-db-to-aks.yml
Labels: deploy, devops

#6443 [690] Allow setting custom domain per environment
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/sandbox.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: devops

#6440 Update confirmation instructions
  app/views/jobseekers/account_mailer/confirmation_instructions.text.erb
  config/locales/mailers.yml
Labels: deploy

#6449 [709] Fix "Host is taken" on review apps
  terraform/workspace-variables/review.tfvars.json
Labels: devops
