Repository DFE-Digital/teaching-vacancies, pull requests merged in 2023-05, with the labels that each got.

#6007 Tweaks for Devcontainer env
  .devcontainer/devcontainer.json
  Gemfile
  Gemfile.lock
Labels: devops

#5991 Add hidden text to invite to apply for job link
  app/views/publishers/jobseeker_profiles/_layout.html.slim
Labels: deploy

#5999 Embed feedback into the job vacancy summary page
  app/controllers/publishers/vacancies/feedbacks_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/form_models/publishers/job_listing/feedback_form.rb
  app/views/publishers/vacancies/feedbacks/new.html.slim
  app/views/publishers/vacancies/summary.html.slim
  config/locales/publishers.yml
  config/routes.rb
  spec/form_models/publishers/job_listing/feedback_form_spec.rb
  spec/system/publishers_can_give_job_listing_feedback_spec.rb
Labels: deploy, ruby

#6008 Re-enable analytics check task
  app/jobs/send_entity_imported_events_to_data_warehouse_job.rb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/analytics_pii.yml
  config/application.rb
  spec/configuration/sidekiq_scheduled_jobs_spec.rb
  spec/jobs/send_entity_imported_events_to_data_warehouse_job_spec.rb
  spec/models/application_record_spec.rb
Labels: deploy

#6020 Customer satisfaction question
  app/controllers/general_feedbacks_controller.rb
  app/form_models/general_feedback_form.rb
  app/views/general_feedbacks/new.html.slim
  config/locales/activerecord.yml
  config/locales/forms.yml
  spec/form_models/general_feedback_form_spec.rb
  spec/system/general_feedback_spec.rb
Labels: deploy

#6031 Disable subject filtering from search keywords
  app/form_models/jobseekers/search_form.rb
  spec/form_models/jobseekers/search_form_spec.rb
  spec/system/jobseekers_can_search_for_jobs_spec.rb
Labels: deploy

#6033 Add Jobseeker account for all team members
  db/seeds.rb
Labels: deploy

#6022 Add occupation and reason to feedback
  app/controllers/general_feedbacks_controller.rb
  app/controllers/jobseekers/account_feedbacks_controller.rb
  app/controllers/jobseekers/job_applications/feedbacks_controller.rb
  app/controllers/jobseekers/subscriptions/feedbacks/further_feedbacks_controller.rb
  app/controllers/jobseekers/unsubscribe_feedbacks_controller.rb
  app/controllers/publishers/vacancies/feedbacks_controller.rb
  app/form_models/general_feedback_form.rb
  app/form_models/jobseekers/account_feedback_form.rb
  app/form_models/jobseekers/job_alert_further_feedback_form.rb
  app/form_models/jobseekers/job_application/feedback_form.rb
  app/form_models/jobseekers/unsubscribe_feedback_form.rb
  app/form_models/publishers/job_listing/feedback_form.rb
  app/views/general_feedbacks/new.html.slim
  app/views/jobseekers/account_feedbacks/new.html.slim
  app/views/jobseekers/job_applications/submit.html.slim
  app/views/jobseekers/subscriptions/feedbacks/further_feedbacks/new.html.slim
  app/views/jobseekers/unsubscribe_feedbacks/new.html.slim
  app/views/publishers/vacancies/summary.html.slim
  config/analytics.yml
  config/locales/activerecord.yml
  config/locales/forms.yml
  db/migrate/20230511113514_add_occupation_to_feedbacks.rb
  db/schema.rb
  spec/form_models/general_feedback_form_spec.rb
  spec/form_models/jobseekers/account_feedback_form_spec.rb
  spec/form_models/jobseekers/job_alert_further_feedback_form_spec.rb
  spec/form_models/jobseekers/job_application/application_feedback_form_spec.rb
  spec/form_models/jobseekers/unsubscribe_feedback_form_spec.rb
  spec/form_models/publishers/job_listing/feedback_form_spec.rb
  spec/system/general_feedback_spec.rb
  spec/system/jobseekers_can_give_account_feedback_spec.rb
  spec/system/jobseekers_can_give_application_feedback_spec.rb
  spec/system/jobseekers_can_give_job_alert_feedback_spec.rb
  spec/system/jobseekers_can_manage_their_job_alerts_from_the_dashboard_spec.rb
  spec/system/jobseekers_can_unsubscribe_from_subscriptions_spec.rb
  spec/system/publishers_can_give_job_listing_feedback_spec.rb
Labels: deploy

#6041 Switch GH actions Rspec format to default progress
  .github/workflows/test.yml
Labels: github-actions

#6042 Rake task to deactivate jobseeker profiles which are currently active…
  lib/tasks/deactivate_incomplete_jobseeker_profiles.rake
Labels: deploy

#6048 Enforce document presence when submitting form
  app/form_models/publishers/job_listing/documents_form.rb
Labels: deploy

#6055 Remove Map from Jobs search results
  app/controllers/vacancies_controller.rb
  app/services/search/vacancy_search.rb
  app/views/vacancies/index.html.slim
Labels: deploy

#6050 Switch filtering order to put education phase above subject
  app/views/vacancies/search/_filters.html.slim
Labels: deploy

#6067 Fix link font size
  app/views/jobseekers/profiles/employments/_summary.html.slim
Labels: deploy
