Repository DFE-Digital/teaching-vacancies, pull requests merged in 2023-07, with the labels that each got.

#6142 Change support dashboard date filtering
  app/controllers/support_users/feedbacks_controller.rb
  app/models/feedback_reporting_period.rb
  app/views/support_users/feedbacks/_reporting_period_control.html.slim
  app/views/support_users/feedbacks/_tables.html.slim
  app/views/support_users/feedbacks/_tabs.html.slim
  spec/models/feedback_reporting_period_spec.rb
  spec/system/support_users/feedback_spec.rb
Labels: deploy

#6150 Fix error on support dashboard date navigation
  app/controllers/support_users/feedbacks_controller.rb
Labels: bug

#6136 Changes to email confirmation flow
  app/controllers/jobseekers/confirmations_controller.rb
  app/controllers/jobseekers/registrations_controller.rb
  app/helpers/notify_views_helper.rb
  app/mailers/jobseekers/devise_emails.rb
  app/views/jobseekers/account_mailer/confirmation_instructions.text.erb
  app/views/jobseekers/accounts/confirmation.html.slim
  app/views/layouts/_flash_messages.html.slim
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  config/locales/mailers.yml
  spec/mailers/jobseekers/account_mailer_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers_can_create_a_job_alert_from_a_search_spec.rb
  spec/system/jobseekers_can_manage_their_job_alerts_from_the_email_spec.rb
  spec/system/jobseekers_can_save_a_job_spec.rb
  spec/system/jobseekers_can_sign_up_to_an_account_spec.rb
  spec/system/jobseekers_can_start_a_job_application_spec.rb
  spec/system/jobseekers_can_unlock_their_account_spec.rb
Labels: deploy

#6161 Add "Quick Apply" tags to vacancies displayed for JobSeekers.
  app/views/organisations/_organisation.html.slim
  app/views/vacancies/listing/_banner.html.slim
  app/views/vacancies/listing/_similar_jobs.html.slim
  app/views/vacancies/search/_results.html.slim
  config/locales/en.yml
  spec/factories/vacancies.rb
  spec/system/jobseekers_can_view_a_vacancy_spec.rb
  spec/system/jobseekers_can_view_all_the_jobs_spec.rb
  spec/system/jobseekers_can_view_an_organisation_spec.rb
Labels: deploy

#6187 Fix: Avoid using sequence for vacancy in prod env
  spec/factories/job_applications.rb
  spec/factories/vacancies.rb
Labels: bug, deploy

#6163 Add quick apply inset text to job alert emails
  app/views/jobseekers/alert_mailer/alert.text.erb
  config/locales/mailers.yml
Labels: deploy

#6189 [491] Create terraform basic resources
  Makefile
  global_config/review_aks.sh
Labels: devops

#6173 Add origin URL to general feedback forms
  app/controllers/general_feedbacks_controller.rb
  app/controllers/jobseekers/account_feedbacks_controller.rb
  app/form_models/general_feedback_form.rb
  app/form_models/jobseekers/account_feedback_form.rb
  app/views/general_feedbacks/new.html.slim
  app/views/jobseekers/account_feedbacks/new.html.slim
  app/views/support_users/feedbacks/_feedback_table.html.slim
  config/analytics.yml
  db/migrate/20230710104904_add_origin_path_to_feedbacks.rb
  db/schema.rb
  spec/system/general_feedback_spec.rb
  spec/system/jobseekers_can_give_account_feedback_spec.rb
  spec/system/support_users/feedback_spec.rb
Labels: deploy

#6126 Redesign and extend cookies banner and preferences
  app/components/cookies_banner_component.rb
  app/components/cookies_banner_component/cookies_banner_component.html.slim
  app/controllers/application_controller.rb
  app/controllers/cookies_preferences_controller.rb
  app/helpers/application_helper.rb
  app/views/cookies_preferences/_cookies_consent_form.html.slim
  app/views/cookies_preferences/new.html.slim
  app/views/layouts/_cookies_banner.html.slim
  app/views/layouts/_skip_links.html.slim
  backstop/lib/playwright/loadCookies.cjs
  config/locales/activerecord.yml
  config/locales/cookies_preferences.yml
  config/locales/en.yml
  spec/components/cookies_banner_component_spec.rb
  spec/requests/cookies_preferences_spec.rb
  spec/system/cookies_banner_spec.rb
  spec/system/cookies_consent_spec.rb
Labels: deploy

#6209 Change filter mapping
  config/search/keyword_filter_mappings.yml
  spec/system/jobseekers_can_search_for_jobs_spec.rb
Labels: deploy

#6218 Remove working patterns again
  app/models/vacancy.rb
  config/landing_pages.yml
  config/locales/landing_pages.yml
  spec/configuration/landing_pages_configuration_spec.rb
Labels: deploy

#6222 Fix homepage translation bug
  app/views/home/_landing_page_links.html.slim
Labels: deploy

#6220 Add ActiveRecord DB consistency tools - Plus fix missing Foreign Keys
  .active_record_doctor
  .database_consistency.todo.yml
  .database_consistency.yml
  Gemfile
  Gemfile.lock
  db/migrate/20230724180457_add_organisations_id_school_group_memberships_school_id_fk.rb
  db/migrate/20230724180458_add_organisations_id_school_group_memberships_school_group_id_fk.rb
  db/migrate/20230724180459_add_vacancies_id_saved_jobs_vacancy_id_fk.rb
  db/migrate/20230724180460_add_organisations_id_publisher_preferences_organisation_id_fk.rb
  db/migrate/20230724180461_add_organisations_id_organisation_vacancies_organisation_id_fk.rb
  db/migrate/20230724180462_add_vacancies_id_organisation_vacancies_vacancy_id_fk.rb
  db/migrate/20230724180463_add_organisations_id_organisation_publisher_preferences_organisation_id_fk.rb
  db/migrate/20230724180464_add_publisher_preferences_id_organisation_publisher_preferences_publisher_preference_id_fk.rb
  db/migrate/20230724180465_add_organisations_id_organisation_publishers_organisation_id_fk.rb
  db/migrate/20230724180466_add_publishers_id_organisation_publishers_publisher_id_fk.rb
  db/migrate/20230724180467_add_publisher_preferences_id_local_authority_publisher_schools_publisher_preference_id_fk.rb
  db/migrate/20230724180468_add_organisations_id_local_authority_publisher_schools_school_id_fk.rb
  db/migrate/20230724180469_add_jobseekers_id_job_applications_jobseeker_id_fk.rb
  db/migrate/20230724180470_add_jobseekers_id_invitation_to_applies_jobseeker_id_fk.rb
  db/migrate/20230724180471_add_jobseeker_profiles_id_employments_jobseeker_profile_id_fk.rb
  db/migrate/20230724180472_add_subscriptions_id_alert_runs_subscription_id_fk.rb
  db/migrate/20230724180473_add_jobseeker_profiles_id_qualifications_jobseeker_profile_id_fk.rb
  db/migrate/20230724180474_add_job_applications_id_feedbacks_job_application_id_fk.rb
  db/migrate/20230724180475_add_jobseekers_id_feedbacks_jobseeker_id_fk.rb
  db/migrate/20230724180476_add_publishers_id_feedbacks_publisher_id_fk.rb
  db/migrate/20230724180477_add_subscriptions_id_feedbacks_subscription_id_fk.rb
  db/migrate/20230724180478_add_vacancies_id_feedbacks_vacancy_id_fk.rb
  db/schema.rb
Labels: deploy

#6226 Vacancy search: few improvements for performance gains
  app/controllers/vacancies_controller.rb
  app/services/search/similar_jobs.rb
  app/services/search/vacancy_search.rb
  app/services/search/wider_suggestions_builder.rb
  app/views/vacancies/index.html.slim
  spec/services/search/vacancy_search_spec.rb
Labels: deploy

#6242 Add missing association indexes in DB
  .database_consistency.todo.yml
  db/migrate/20230725115015_add_feedbacks_subscription_id_index.rb
  db/migrate/20230725115016_add_organisation_publisher_preferences_publisher_preference_id_index.rb
  db/migrate/20230725115017_add_local_authority_publisher_schools_publisher_preference_id_index.rb
  db/migrate/20230725115018_add_personal_details_jobseeker_profile_id_index.rb
  db/migrate/20230725115019_add_job_preferences_jobseeker_profile_id_index.rb
  db/migrate/20230725115020_add_feedbacks_job_application_id_index.rb
  db/migrate/20230725115021_add_friendly_id_slugs_sluggable_id_sluggable_type_index.rb
  db/migrate/20230725115022_add_saved_jobs_vacancy_id_index.rb
  db/migrate/20230725115023_add_equal_opportunities_reports_vacancy_id_index.rb
  db/migrate/20230725115024_add_feedbacks_publisher_id_index.rb
  db/migrate/20230725115025_add_organisation_publishers_publisher_id_index.rb
  db/migrate/20230725115026_add_feedbacks_jobseeker_id_index.rb
  db/migrate/20230725115027_add_job_applications_jobseeker_id_index.rb
  db/migrate/20230725115028_add_jobseeker_profiles_jobseeker_id_index.rb
  db/migrate/20230725115029_add_organisation_publishers_organisation_id_index.rb
  db/schema.rb
  spec/models/personal_details_spec.rb
Labels: deploy

#6250 Align PostgreSQL QA/Review version with other envs
  terraform/app/variables.tf
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/review.tfvars.json
Labels: deploy
