Repository DFE-Digital/teaching-vacancies, pull requests merged in 2023-04, with the labels that each got.

#5918 [258] Only show full time and part time on subscription form
  app/form_models/jobseekers/subscription_form.rb
Labels: deploy

#5920 [260] Use consistent validation errors on pay package form
  config/locales/activerecord.yml
Labels: deploy

#5919 [259] Hide certain job application fields on publisher side if blank
  app/controllers/concerns/authenticated.rb
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
  app/views/jobseekers/job_applications/review/_personal_details.html.slim
Labels: deploy

#5896 Displaying more detailed school type on school profile
  app/helpers/organisations_helper.rb
  app/views/organisations/_organisation.html.slim
  config/locales/organisations.yml
Labels: deploy

#5925 [TRELLO #262] Show qualification name instead of "other" category
  app/helpers/qualifications_helper.rb
  app/views/jobseekers/job_applications/review/_qualifications.html.slim
Labels: deploy

#5931 Update gems
  Gemfile.lock
  app/views/jobseekers/profiles/personal_details/work.html.slim
  spec/system/publishers_can_view_a_job_application_spec.rb
Labels: deploy

#5973 Explicitly ignore specific markdown files.
  .github/workflows/build_and_deploy.yml
Labels: github-actions

#5971 Avoid Redis and Sidekiq major version Dependabot upgrades
  .github/dependabot.yml
Labels: dependencies

#5987 Upgrade npm jest to v29.5.0
  package.json
  yarn.lock
Labels: dependencies
