Repository DFE-Digital/teaching-vacancies, pull requests merged in 2023-10, with the labels that each got.

#6456 Add a env var for disabling ActionMailer
  .env.development
  .env.example
  .env.test
  config/application.rb
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
  terraform/workspace-variables/dev_app_env.yml
  terraform/workspace-variables/production_app_env.yml
  terraform/workspace-variables/qa_app_env.yml
  terraform/workspace-variables/review_app_env.yml
  terraform/workspace-variables/sandbox_app_env.yml
  terraform/workspace-variables/staging_app_env.yml
Labels: deploy

#6463 [707] Fix missing aks_web_app_instances variable
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/variables.tf
  terraform/workspace-variables/production_app_env.yml
Labels: devops

#6447 Add subjects to jobseeker profiles
  app/controllers/jobseekers/profiles/employments_controller.rb
  app/form_models/jobseekers/profile/employment_form.rb
  app/views/jobseekers/employments/_employments.html.slim
  app/views/jobseekers/profiles/_summary.html.slim
  app/views/jobseekers/profiles/employments/_fields.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers/prefilling_applications_spec.rb
  spec/system/jobseekers_can_add_employments_to_their_job_application_spec.rb
  spec/system/publishers/publishers_can_view_a_jobseeker_profile_spec.rb
Labels: deploy

#6464 Remove pinned gem versions
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#6459 Change wording on QTS question
  app/views/jobseekers/job_applications/build/professional_status.html.slim
  app/views/jobseekers/profiles/qualified_teacher_status/edit.html.slim
  config/locales/forms.yml
Labels: deploy

#6467 Validate email address for jobseekers
  app/jobs/delete_jobseekers_with_incorrect_emails_job.rb
  app/models/jobseeker.rb
  config/schedule.yml
  spec/services/email_address_audit_spec.rb
Labels: deploy

#6475 Add hidden text to change links on school profile page
  app/views/publishers/organisations/_organisation.html.slim
Labels: deploy

#6483 Automate getting cluster credentials on Makefile
  Makefile
Labels: devops

#6489 Migrate Smoke tests from PaaS to AKS hosting
  .github/actions/smoke-test/action.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/smoke-test.yml
  spec/smoke_tests/jobseekers_can_view_homepage_spec.rb
Labels: deploy, ruby, devops

#6364 Add Ark Vacancy Source
  .env.test
  app/jobs/import_from_vacancy_sources_job.rb
  app/vacancy_sources/vacancy_source/source/ark.rb
  app/validators/external_vacancy_validator.rb
  spec/fixtures/files/vacancy_sources/ark.xml
  spec/vacancy_sources/vacancy_source/source/ark_spec.rb
Labels: deploy

#6493 Upgrade docs hosting info
  README.md
  documentation/aks.md
  documentation/alert-runbook.md
  documentation/database-backups.md
  documentation/deployments.md
  documentation/disaster-recovery.md
  documentation/docker.md
  documentation/dsi-integration.md
  documentation/hosting.md
  documentation/infrastructure.md
  documentation/maintenance-mode.md
  documentation/monitoring.md
  documentation/offline-site.md
  documentation/onboarding.md
  documentation/rollback.md
  documentation/simulate-data-loss-disaster.md
  documentation/terraform.md
Labels: deploy

#6503 Fix OpenSSL vulnerable version in docker image
  Dockerfile
Labels: deploy, devops

#6495 Ensure that a jobseekers work history is displayed with the most rece…
  app/services/jobseekers/job_applications/employment_gap_finder.rb
  app/views/jobseekers/job_applications/build/employment_history.html.slim
  app/views/jobseekers/job_applications/review/_employment_history.html.slim
  app/views/jobseekers/profiles/_summary.html.slim
  config/locales/forms.yml
  spec/services/jobseekers/job_applications/employment_gap_finder_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers_can_add_employments_to_their_job_application_spec.rb
  spec/system/jobseekers_can_complete_a_job_application_spec.rb
  spec/system/jobseekers_can_review_a_job_application_spec.rb
  spec/system/jobseekers_can_view_a_job_application_spec.rb
  spec/system/publishers_can_view_a_job_application_spec.rb
Labels: deploy

#6502 Rename docker image refs in infra code
  Makefile
  documentation/terraform.md
  terraform/app/terraform.tf
  terraform/app/variables.tf
Labels: deploy

#6497 change expiry times
  app/models/vacancy.rb
  config/locales/forms.yml
  spec/support/vacancy_helpers.rb
  spec/system/publishers_can_publish_a_vacancy_as_a_school_spec.rb
Labels: deploy
