Repository DFE-Digital/teaching-vacancies, pull requests merged in 2024-08, with the labels that each got.

#6991 Changes to the apply to jobs page
  app/views/vacancies/listing/_job_details.html.slim
  config/locales/jobs.yml
  config/locales/jobseekers.yml
Labels: deploy

#6994 Fixing typo on jobshare question
  app/views/publishers/vacancies/build/working_patterns.html.slim
Labels: deploy

#6987 Update job alerts email
  app/helpers/notify_views_helper.rb
  app/views/jobseekers/alert_mailer/alert.text.erb
  config/locales/mailers.yml
  spec/mailers/jobseekers/alert_mailer_spec.rb
Labels: deploy

#6995 Hiring staff sign in journey
  app/views/publishers/sessions/new.html.slim
  app/views/publishers/vacancies/build/job_title.html.slim
  config/locales/publishers.yml
Labels: deploy

#6996 Add hint text to the school offer text area
  app/components/editor_component/editor_component.html.slim
  app/views/publishers/vacancies/build/about_the_role.html.slim
  config/locales/jobs.yml
Labels: deploy

#7004 Fix filter bug
  app/queries/vacancy_filter_query.rb
  spec/queries/vacancy_filter_query_spec.rb
Labels: deploy

#6944 Remove references to flexible or term_time working patterns
  app/form_models/jobseekers/job_preferences_form.rb
  app/form_models/publishers/jobseeker_profile_search_form.rb
  app/models/vacancy.rb
  app/presenters/vacancy_presenter.rb
  app/views/home/_landing_page_links.html.slim
  config/landing_pages.yml
  config/locales/forms.yml
  config/locales/publishers.yml
  config/search/keyword_filter_mappings.yml
  spec/helpers/vacancies_helper_spec.rb
  spec/services/vacancies/import/sources/united_learning_spec.rb
Labels: deploy

#7003 Setup Rails credentials with OneLogin keys
  .gitattributes
  config/credentials.yml.enc
  config/environments/production.rb
Labels: deploy, devops

#7013 Small content tweaks
  config/locales/activerecord.yml
  config/locales/jobseekers.yml
  spec/system/jobseekers/jobseekers_can_manage_a_profile_spec.rb
Labels: deploy

#7018 [1839] Update terraform providers
  terraform/app/.terraform.lock.hcl
  terraform/app/modules/cloudfront/versions.tf
  terraform/app/modules/cloudwatch/versions.tf
  terraform/app/modules/paas/versions.tf
  terraform/app/modules/statuscake/versions.tf
  terraform/app/versions.tf
  terraform/common/.terraform.lock.hcl
  terraform/common/modules/domains/versions.tf
  terraform/common/s3.tf
  terraform/common/versions.tf
Labels: devops
