Repository DFE-Digital/teaching-vacancies, pull requests merged in 2024-03, with the labels that each got.

#6680 Reinstate Flexible/Term time/Job share working patterns
  app/controllers/concerns/publishers/wizardable.rb
  app/form_models/jobseekers/job_preferences_form.rb
  app/form_models/jobseekers/subscription_form.rb
  app/form_models/publishers/job_listing/working_patterns_form.rb
  app/form_models/publishers/jobseeker_profile_search_form.rb
  app/helpers/landing_pages_helper.rb
  app/helpers/vacancies_helper.rb
  app/models/vacancy.rb
  app/presenters/vacancy_presenter.rb
  app/queries/vacancy_filter_query.rb
  app/services/copy_vacancy.rb
  app/vacancy_sources/vacancy_source/source/united_learning.rb
  app/views/home/_landing_page_links.html.slim
  app/views/publishers/vacancies/build/working_patterns.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_job_details.html.slim
  config/landing_pages.yml
  config/locales/activerecord.yml
  config/locales/forms.yml
  config/locales/jobs.yml
  config/locales/publishers.yml
  config/search/keyword_filter_mappings.yml
  lib/tasks/update_subscription_legacy_search_criteria.rake
  spec/configuration/landing_pages_configuration_spec.rb
  spec/factories/job_preferences.rb
  spec/factories/vacancies.rb
  spec/form_models/publishers/job_listing/working_patterns_form_spec.rb
  spec/helpers/landing_pages_helper_spec.rb
  spec/helpers/vacancies_helper_spec.rb
  spec/jobs/import_from_vacancy_source_job_spec.rb
  spec/lib/update_subscription_search_criteria_spec.rb
  spec/presenters/vacancy_presenter_spec.rb
  spec/support/vacancy_helpers.rb
  spec/vacancy_sources/vacancy_source/source/united_learning_spec.rb
Labels: deploy

#6706 Right to work question
  app/views/jobseekers/_visa_sponsorship_banner.html.slim
  app/views/jobseekers/job_applications/index.html.slim
  app/views/jobseekers/profiles/personal_details/work.html.slim
  app/views/jobseekers/saved_jobs/index.html.slim
  config/locales/en.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  config/locales/publishers.yml
  spec/system/jobseekers/jobseekers_can_manage_a_profile_spec.rb
Labels: deploy

#6717 Correctly display safeguarding issues answer on application review page
  app/helpers/job_applications_helper.rb
Labels: deploy

#6718 Fix Publisher email code backup sign-in flow
  app/controllers/publishers/login_keys_controller.rb
  app/form_models/publishers/login_keys/choose_organisation_form.rb
  app/views/publishers/login_keys/error.html.slim
  app/views/publishers/login_keys/show.html.slim
  config/brakeman.ignore
  config/locales/activerecord.yml
  config/locales/publishers.yml
  config/routes.rb
  spec/system/other/users_can_only_be_signed_in_to_one_type_of_account_spec.rb
  spec/system/publishers/publishers_can_sign_in_by_email_spec.rb
Labels: deploy

#6720 Add hint text to publisher working patterns step
  app/views/publishers/vacancies/build/working_patterns.html.slim
  config/locales/forms.yml
Labels: deploy

#6725 Fix visa sponsorship bug
  app/helpers/job_applications_helper.rb
  app/views/jobseekers/job_applications/review/_personal_details.html.slim
Labels: deploy

#6723 Set default safe guarding information for organisations
  db/migrate/20240308173633_add_default_safe_guarding_information_to_organisations.rb
  db/schema.rb
  lib/tasks/data.rake
Labels: deploy

#6727 Protect non production environments with password
  .github/actions/smoke-test/action.yml
  .github/workflows/build_and_deploy.yml
  app/controllers/application_controller.rb
  spec/smoke_tests/jobseekers_can_view_homepage_spec.rb
Labels: deploy

#6731 Status indicators
  app/controllers/jobseekers/job_applications_controller.rb
  app/helpers/status_tag_helper.rb
  app/models/job_application.rb
  app/services/jobseekers/job_applications/quick_apply.rb
  spec/helpers/status_tag_helper_spec.rb
  spec/services/jobseekers/job_applications/quick_apply_spec.rb
  spec/system/jobseekers/jobseeker_applications_statuses_spec.rb
Labels: deploy

#6737 Vacancy filtering bug
  app/queries/vacancy_filter_query.rb
  spec/queries/vacancy_filter_query_spec.rb
Labels: deploy

#6739 Update profiles from job application submissions
  app/controllers/jobseekers/job_applications_controller.rb
  app/form_models/jobseekers/job_application/review_form.rb
  app/models/jobseeker_profile.rb
  app/views/jobseekers/job_applications/review.html.slim
  app/views/jobseekers/job_applications/submit.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  spec/models/jobseeker_profile_spec.rb
  spec/system/jobseekers/jobseekers_can_update_their_profile_from_job_applications_spec.rb
Labels: deploy

#6743 Add banner and hiring guide for ASR
  app/components/dashboard_component/dashboard_component.html.slim
  app/views/content/get-help-hiring/how-to-list-non-teaching-roles.md
  config/locales/jobs.yml
Labels: deploy

#6738 Use role names in yaml files to correctly render role names on hiring…
  app/helpers/landing_pages_helper.rb
  app/views/jobseekers/profiles/_summary.html.slim
  app/views/publishers/jobseeker_profiles/search/_results.html.slim
  spec/support/vacancy_helpers.rb
  spec/system/jobseekers/jobseekers_can_view_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_preview_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_search_for_jobseeker_profiles_spec.rb
  spec/system/publishers/publishers_can_view_a_jobseeker_profile_spec.rb
Labels: deploy

#6745 Upgrade Hosting/Onboarding docs with latest PIM groups
  documentation/hosting.md
  documentation/onboarding.md
Labels: devops

#6746 Fix healthcheck for Review App deletion action
  .github/workflows/delete_review_app.yml
Labels: devops

#6747 Enable to skip the status check when manually deleting review apps
  .github/workflows/delete_review_app.yml
Labels: devops

#6750 Do not show professional status for not teaching roles
  app/views/jobseekers/job_applications/_show.html.slim
  spec/system/jobseekers/jobseekers_can_view_a_job_application_spec.rb
Labels: deploy

#6754 fix snyk issue with gnutls
  Dockerfile
Labels: deploy

#6755 Introduce Recaptcha v3 check with v2 fallback
  app/controllers/concerns/recaptcha_checking.rb
  app/controllers/errors_controller.rb
  app/controllers/general_feedbacks_controller.rb
  app/controllers/jobseekers/subscriptions/feedbacks/further_feedbacks_controller.rb
  app/controllers/subscriptions_controller.rb
  app/controllers/support_requests_controller.rb
  app/helpers/application_helper.rb
  app/views/errors/invalid_recaptcha.html.slim
  app/views/general_feedbacks/new.html.slim
  app/views/jobseekers/subscriptions/feedbacks/further_feedbacks/new.html.slim
  app/views/shared/_recaptcha.html.slim
  app/views/subscriptions/new.html.slim
  app/views/support_requests/new.html.slim
  config/initializers/recaptcha.rb
  config/locales/en.yml
  config/locales/forms.yml
  config/routes.rb
  spec/controllers/jobseekers/subscriptions_controller_spec.rb
  spec/factories/feedbacks.rb
  spec/fixtures/vcr/Requesting_support/when_recaptcha_is_invalid/logs_the_invalid_recaptcha_while_still_recording_the_support_request.yml
  spec/helpers/application_helper_spec.rb
  spec/requests/errors_spec.rb
  spec/requests/recaptcha_spec.rb
  spec/system/jobseekers/jobseekers_can_create_a_job_alert_from_a_search_spec.rb
  spec/system/jobseekers/jobseekers_can_create_a_job_alert_from_the_dashboard_spec.rb
  spec/system/jobseekers/jobseekers_can_give_job_alert_feedback_spec.rb
  spec/system/other/general_feedback_spec.rb
  spec/system/other/get_help_spec.rb
  spec/system/support_users/feedback_spec.rb
Labels: deploy, ruby
