Repository DFE-Digital/teaching-vacancies, pull requests merged in 2024-06, with the labels that each got.

#6883 Copy training and cpds from previous application into new application
  app/services/jobseekers/job_applications/quick_apply.rb
  spec/factories/job_applications.rb
  spec/factories/training_and_cpds.rb
  spec/services/jobseekers/job_applications/quick_apply_spec.rb
Labels: deploy

#6886 Change hint text on visa sponsorship page
  app/views/publishers/vacancies/build/visa_sponsorship.html.slim
  config/locales/publishers.yml
Labels: deploy

#6895 Upgrade to Ruby 3.3.2
  .devcontainer/Dockerfile
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: deploy

#6882 [1812] Enable Logit.io for non-prod environments
  terraform/app/.terraform.lock.hcl
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/qa.tfvars.json
  terraform/workspace-variables/review.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: deploy

#6898 Fix links in publisher job application email alerts
  app/helpers/notify_views_helper.rb
  spec/mailers/publishers/job_application_mailer_spec.rb
  spec/system/publishers/publishers_get_email_notifications_from_job_applications_spec.rb.rb
Labels: bug

#6899 Fix bug on "humanize_array" helper
  app/helpers/vacancies_helper.rb
  spec/helpers/vacancies_helper_spec.rb
Labels: bug

#6903 Add ASAP to the start date options
  app/models/vacancy.rb
  app/views/publishers/vacancies/build/start_date.html.slim
  app/views/publishers/vacancies/extend_deadline/show.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_important_dates.html.slim
  app/views/vacancies/listing/_key_dates_sidebar.html.slim
  config/locales/forms.yml
  spec/support/vacancy_helpers.rb
  spec/system/jobseekers/jobseekers_can_view_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
Labels: deploy

#6910 Upgrade busybox package in dockerfile to fix snyk issue
  Dockerfile
Labels: deploy

#6909 Feedback update
  app/helpers/notify_views_helper.rb
  app/jobs/send_expired_vacancy_feedback_prompt_job.rb
  app/mailers/publishers/expired_vacancy_feedback_prompt_mailer.rb
  app/views/publishers/expired_vacancy_feedback_prompt_mailer/prompt_for_feedback.text.erb
  app/views/publishers/vacancies/summary.html.slim
  config/locales/forms.yml
  config/locales/mailers.yml
  config/locales/publishers.yml
  spec/jobs/send_expired_vacancy_feedback_email_prompt_job_spec.rb
  spec/mailers/publishers/expired_vacancy_feedback_prompt_mailer_spec.rb
  spec/system/publishers/publishers_can_provide_feedback_on_expired_vacancies_via_prompt_email_spec.rb
Labels: deploy

#6922 [1912] Ship production logs to Logit.io
  terraform/workspace-variables/production.tfvars.json
Labels: devops

#6927 Upgrade Ruby to v3.3.3
  .devcontainer/Dockerfile
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: devops

#6925 Application data saving content changes
  app/views/content/jobseeker-guides/3-quick-ways-to-find-the-right-teaching-job.md
  config/locales/forms.yml
  config/locales/jobseekers.yml
  spec/system/jobseekers/prefilling_applications_spec.rb
Labels: deploy

#6933 Schedule export service to DWP find a job
  app/jobs/export_vacancies_closed_early_since_yesterday_to_dwp_find_a_job_service_job.rb
  app/jobs/export_vacancies_published_and_updated_since_yesterday_to_dwp_find_a_job_service_job.rb
  config/schedule.yml
  documentation/integrations/dwp-find-a-job.md
  spec/jobs/export_vacancies_closed_early_since_yesterday_to_dwp_find_a_job_service_job_spec.rb
  spec/jobs/export_vacancies_published_and_updated_since_yesterday_to_dwp_find_a_job_service_job_spec.rb
Labels: deploy

#6935 Remove line breaks from jobs sent to find a job service
  app/services/vacancies/export/dwp_find_a_job/published_and_updated_vacancies/parsed_vacancy.rb
  spec/services/vacancies/export/dwp_find_a_job/published_and_updated_vacancies/parsed_vacancy_spec.rb
Labels: bug
