Repository DFE-Digital/teaching-vacancies, pull requests merged in 2025-05, with the labels that each got.

#7713 Vacancies / School search filters mobile rendering
  app/assets/stylesheets/components/filters.scss
  app/controllers/organisations_controller.rb
  app/form_models/jobseekers/search_form.rb
  app/form_models/school_search_form.rb
  app/views/organisations/index.html.slim
  app/views/organisations/search/_filters.html.slim
  app/views/organisations/search/_form.html.slim
  app/views/organisations/search/_open_filters_button.html.slim
  app/views/vacancies/campaign_landing_page.html.slim
  app/views/vacancies/index.html.slim
  app/views/vacancies/search/_filters.html.slim
  app/views/vacancies/search/_open_filters_button.html.slim
  config/locales/en.yml
  config/locales/forms.yml
  spec/form_models/jobseekers/search_form_spec.rb
  spec/form_models/school_search_form_spec.rb
  spec/support/shared_examples/mobile_filters.rb
  spec/system/jobseekers/jobseekers_can_search_for_jobs_spec.rb
  spec/system/jobseekers/jobseekers_can_search_for_schools_spec.rb
  spec/views/organisations/index.html.slim_spec.rb
  spec/views/vacancies/index.html.slim_spec.rb
Labels: deploy

#7708 Jobs management pagination
  app/components/dashboard_component.rb
  app/controllers/publishers/vacancies_controller.rb
  app/views/publishers/vacancies/index.html.slim
  config/brakeman.ignore
  spec/components/dashboard_component_spec.rb
Labels: deploy

#7691 Update accepting-job-applications-on-teaching-vacancies.md
  app/views/content/get-help-hiring/how-to-create-job-listings-and-accept-applications/accepting-job-applications-on-teaching-vacancies.md
Labels: deploy

#7719 Change step ordering
  .simplecov
  app/services/publishers/vacancies/vacancy_step_process.rb
  app/views/publishers/vacancies/_sections.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_about_the_role.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_application_process.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_important_dates.html.slim
  app/views/publishers/vacancies/vacancy_review_sections/_job_details.html.slim
  spec/services/publishers/vacancies/vacancy_step_process_spec.rb
  spec/support/vacancy_helpers.rb
  spec/system/publishers/publishers_can_copy_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_edit_a_draft_vacancy_spec.rb
  spec/system/publishers/publishers_can_edit_a_published_vacancy_as_a_school_group_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_local_authority_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
Labels: deploy

#7743 Review app deletion improvements
  .github/workflows/build_and_deploy.yml
  .github/workflows/delete_review_app.yml
Labels: deploy, devops, github-actions

#7721 Job listing task list
  .simplecov
  app/controllers/concerns/publishers/wizardable.rb
  app/controllers/publishers/vacancies/build_controller.rb
  app/controllers/publishers/vacancies/wizard_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/helpers/status_tag_helper.rb
  app/helpers/vacancy_forms_helper.rb
  app/services/step_process.rb
  app/views/publishers/vacancies/_review_banner.html.slim
  app/views/publishers/vacancies/_review_breadcrumbs.html.slim
  app/views/publishers/vacancies/review_banners/_closed.html.slim
  app/views/publishers/vacancies/review_banners/_complete_draft.html.slim
  app/views/publishers/vacancies/review_banners/_incomplete_draft.html.slim
  app/views/publishers/vacancies/review_banners/_published.html.slim
  app/views/publishers/vacancies/review_banners/_scheduled.html.slim
  app/views/publishers/vacancies/show.html.slim
  config/locales/en.yml
  config/locales/publishers.yml
  config/routes.rb
  spec/factories/vacancies.rb
  spec/helpers/vacancies_helper_spec.rb
  spec/requests/publishers/vacancies/build_spec.rb
  spec/services/step_process_spec.rb
  spec/support/vacancy_helpers.rb
  spec/system/publishers/publishers_can_add_additional_documents_to_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_copy_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_edit_a_draft_vacancy_spec.rb
  spec/system/publishers/publishers_can_edit_a_published_vacancy_as_a_school_group_spec.rb
  spec/system/publishers/publishers_can_edit_a_published_vacancy_as_a_school_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_local_authority_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
  spec/system/publishers/publishers_can_view_their_notifications_spec.rb
  spec/views/publishers/vacancies/show.html.slim_spec.rb
Labels: deploy

#7740 Add optional month for non secondary qualification
  app/controllers/jobseekers/job_applications/qualifications_controller.rb
  app/form_models/jobseekers/qualifications/qualification_form.rb
  app/helpers/pdf_helper.rb
  app/models/qualification.rb
  app/views/jobseekers/job_applications/build/qualifications.html.slim
  app/views/jobseekers/job_applications/review/qualifications/_qualification.html.slim
  app/views/jobseekers/job_applications/review/qualifications/_secondary_qualification.html.slim
  app/views/jobseekers/qualifications/_preview_qualifications.html.slim
  app/views/jobseekers/qualifications/_qualifications.html.slim
  app/views/jobseekers/qualifications/fields/_degree.html.slim
  app/views/jobseekers/qualifications/fields/_other.html.slim
  app/views/jobseekers/qualifications/fields/_secondary_school.html.slim
  app/views/jobseekers/qualifications/review/_qualification.html.slim
  app/views/jobseekers/qualifications/review/_secondary_qualification.html.slim
  config/analytics.yml
  config/locales/forms.yml
  db/migrate/20250430141711_add_month_to_qualifications.rb
  db/schema.rb
  spec/factories/qualifications.rb
  spec/form_models/jobseekers/qualifications/qualification_form_spec.rb
  spec/models/qualification_spec.rb
  spec/requests/jobseekers/job_applications/qualifications_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/publishers/publishers_can_manage_job_applications_for_a_vacancy_spec.rb
Labels: deploy

#7754 Allow ats api to accept empty array for subjects and key stages
  spec/requests/publishers/ats_api/v1/vacancies_spec.rb
  spec/swagger_helper.rb
Labels: deploy

#7756 Add new bespoke pages to campaigns
  config/campaign_pages.yml
  config/locales/campaign_pages.yml
Labels: deploy

#7727 Job application PDF
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/helpers/job_applications_helper.rb
  app/helpers/pdf_helper.rb
  app/helpers/pdf_ui_helper.rb
  app/models/job_application_pdf.rb
  app/services/job_application_pdf_generator.rb
  app/views/jobseekers/job_applications/_explained_employment_break.html.slim
  app/views/jobseekers/job_applications/_unexplained_employment_break.html.slim
  spec/factories/employments.rb
  spec/helpers/pdf_helper_spec.rb
  spec/helpers/pdf_ui_helper_spec.rb
  spec/models/job_application_pdf_spec.rb
  spec/requests/publishers/vacancies/job_applications_spec.rb
  spec/services/job_application_pdf_generator_spec.rb
Labels: deploy

#7761 [bugfix]: Copy records using #duplicate rather than #dup
  .simplecov
  app/controllers/jobseekers/job_applications_controller.rb
  app/models/concerns/application_and_profile_associated_record.rb
  app/models/employment.rb
  app/models/jobseeker_profile.rb
  app/models/professional_body_membership.rb
  app/models/qualification.rb
  app/models/qualification_result.rb
  app/models/reference.rb
  app/models/training_and_cpd.rb
  app/services/jobseekers/job_applications/prefill_job_application_from_jobseeker_profile.rb
  app/services/jobseekers/job_applications/prefill_job_application_from_previous_application.rb
  app/services/jobseekers/job_applications/quick_apply.rb
  db/seeds.rb
  lib/tasks/remove_double_linked_associations.rake
  spec/factories/jobseeker_profiles.rb
  spec/models/employment_spec.rb
  spec/models/jobseeker_profile_spec.rb
  spec/models/qualification_spec.rb
  spec/services/jobseekers/job_applications/prefill_job_application_from_jobseeker_profile_spec.rb
  spec/services/jobseekers/job_applications/prefill_job_application_from_previous_application_spec.rb
  spec/services/jobseekers/job_applications/quick_apply_spec.rb
  spec/system/jobseekers/jobseekers_can_add_qualifications_to_their_profile_spec.rb
  spec/system/jobseekers/jobseekers_can_update_their_profile_from_job_applications_spec.rb
  spec/system/jobseekers/prefilling_applications_spec.rb
Labels: deploy

#7776 Fix libxml2 package version to avoid vulnerability
  Dockerfile
Labels: deploy

#7775 Fix ECT status filter from Campaign config criteria
  app/services/campaign_search_params_merger.rb
  config/campaign_pages.yml
  spec/services/campaign_page_spec.rb
  spec/services/campaign_search_params_merger_spec.rb
Labels: bug, deploy

#7780 Fix peak reminder email when jobseeker has no name
  app/mailers/jobseekers/peak_times_mailer.rb
  app/views/jobseekers/peak_times_mailer/reminder.text.erb
  config/locales/mailers.yml
  spec/mailers/jobseekers/peak_times_mailer_spec.rb
Labels: bug

#7741 convert system test to view spec
  app/controllers/publishers/vacancies/job_applications/base_controller.rb
  app/controllers/publishers/vacancies/job_applications/notes_controller.rb
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/views/jobseekers/job_applications/review/_declarations.html.slim
  app/views/publishers/vacancies/_review_banner.html.slim
  app/views/publishers/vacancies/_sections.html.slim
  app/views/publishers/vacancies/build/important_dates.html.slim
  app/views/publishers/vacancies/job_applications/_application_details_and_notes.html.slim
  app/views/publishers/vacancies/job_applications/show.html.slim
  app/views/publishers/vacancies/show.html.slim
  spec/factories/vacancies.rb
  spec/page_objects/pages/application.rb
  spec/page_objects/pages/publisher/application_form_page.rb
  spec/page_objects/pages/publisher/contract_information_page.rb
  spec/page_objects/pages/publisher/important_dates_page.rb
  spec/page_objects/pages/publisher/vacancy_page.rb
  spec/rails_helper.rb
  spec/support/vacancy_helpers.rb
  spec/system/jobseekers/jobseekers_can_search_for_schools_spec.rb
  spec/system/publishers/publishers_can_edit_a_draft_vacancy_spec.rb
  spec/system/publishers/publishers_can_edit_a_published_vacancy_as_a_school_spec.rb
  spec/system/publishers/publishers_can_manage_job_applications_for_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_local_authority_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_school_spec.rb
  spec/system/publishers/publishers_can_publish_a_vacancy_as_a_trust_spec.rb
  spec/system/publishers/publishers_can_view_a_job_application_spec.rb
  spec/views/publishers/vacancies/job_applications/show.html.slim_spec.rb
  spec/views/publishers/vacancies/show.html.slim_spec.rb
  spec/views/vacancies/show.html.slim_spec.rb
Labels: deploy

#7794 Use Geocoding Coordinates for "within UK validator"
  app/validators/within_united_kingdom_validator.rb
  lib/geocoding.rb
  spec/form_models/jobseekers/subscription_form_spec.rb
  spec/lib/geocoding_spec.rb
  spec/rails_helper.rb
  spec/system/jobseekers/jobseekers_can_create_a_job_alert_from_a_search_spec.rb
  spec/system/jobseekers/jobseekers_can_manage_a_profile_spec.rb
  spec/validators/within_united_kingdom_validator_spec.rb
Labels: deploy
