Repository DFE-Digital/teaching-vacancies, pull requests merged in 2025-06, with the labels that each got.

#7798 Pass extra `origin` params
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/views/publishers/vacancies/job_applications/_candidates.html.slim
  app/views/publishers/vacancies/job_applications/index.html.slim
  app/views/publishers/vacancies/job_applications/tag.html.slim
  spec/requests/publishers/vacancies/job_applications_spec.rb
  spec/system/publishers/publishers_can_manage_job_applications_for_a_vacancy_spec.rb
Labels: deploy

#7792 New GDS file uploader component (Mar 25) with increase in size to 20MB
  Gemfile
  Gemfile.lock
  app/assets/javascript/application.js
  app/assets/javascript/init-moj-front-end.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/moj-frontend.scss
  app/components/vacancy_form_page_heading_component.rb
  app/controllers/publishers/vacancies/documents_controller.rb
  app/form_models/base_form.rb
  app/form_models/jobseekers/job_application/catholic_form.rb
  app/form_models/publishers/job_listing/application_form_form.rb
  app/form_models/publishers/job_listing/documents_form.rb
  app/models/vacancy.rb
  app/validators/virus_free_validator.rb
  app/views/jobseekers/job_applications/build/catholic.html.slim
  app/views/publishers/organisations/logo/edit.html.slim
  app/views/publishers/organisations/photo/edit.html.slim
  app/views/publishers/vacancies/build/application_form.html.slim
  app/views/publishers/vacancies/documents/new.html.slim
  app/views/support_requests/new.html.slim
  config/locales/activerecord.yml
  config/locales/forms.yml
  config/locales/publishers.yml
  package.json
  spec/form_models/publishers/job_listing/documents_form_spec.rb
  spec/requests/publishers/vacancies/documents_spec.rb
  spec/services/publishers/document_virus_check_spec.rb
  yarn.lock
Labels: deploy

#7802 Fix bug that removed the publish date on already published vacancies
  .simplecov
  app/form_models/publishers/job_listing/important_dates_form.rb
  app/models/published_vacancy.rb
  app/models/vacancy.rb
  lib/tasks/backfill_vacancies_with_missing_publish_dates.rake
  spec/form_models/publishers/job_listing/important_dates_form_spec.rb
  spec/models/vacancy_spec.rb
  spec/services/publishers/ats_api/update_vacancy_service_spec.rb
Labels: bug, deploy

#7833 seperate job preferences with ", " rather than <br> tags
  app/views/jobseekers/profiles/job_preferences/_summary.html.slim
  spec/system/jobseekers/jobseekers_can_manage_a_profile_spec.rb
Labels: deploy

#7858 use secret rather than ENV/ARG for RAILS_MASTER_KEY
  .github/workflows/build_and_deploy.yml
  Dockerfile
Labels: deploy

#7807 Notify before references are sought
  app/form_models/jobseekers/job_application/referees_form.rb
  app/models/job_application_pdf.rb
  app/views/jobseekers/job_applications/build/referees.html.slim
  app/views/jobseekers/job_applications/referees/edit.html.slim
  app/views/jobseekers/job_applications/referees/new.html.slim
  app/views/jobseekers/job_applications/review/_references.html.slim
  config/analytics.yml
  config/locales/jobseekers.yml
  config/locales/jobseekers/job_application/references_form.yml
  db/migrate/20250602150519_add_notify_before_contact_referers_to_job_application.rb
  db/schema.rb
  lib/tasks/backfil_job_application_notify_before_contact_referers.rake
  spec/factories/job_applications.rb
  spec/form_models/jobseekers/job_application/referees_form_spec.rb
  spec/models/job_application_pdf_spec.rb
Labels: deploy

#7859 Add db workflows
  .github/workflows/backup_db.yml
  .github/workflows/restore-db-ptr.yml
  .github/workflows/restore-db.yml
Labels: deploy, devops

#7874 Add maintenance workflows
  .github/workflows/maintenance.yml
  Makefile
  maintenance_page/Dockerfile
  maintenance_page/html/assets/fonts/bold-affa96571d-v2-b092ddd6.woff
  maintenance_page/html/assets/fonts/bold-b542beb274-v2-616e5f21.woff2
  maintenance_page/html/assets/fonts/light-94a07e06a1-v2-bb962e0c.woff2
  maintenance_page/html/assets/fonts/light-f591b13f7d-v2-f03d82c2.woff
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.br
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.gz
  maintenance_page/html/assets/images/favicon-ec189703.svg
  maintenance_page/html/assets/images/favicon-ec189703.svg.br
  maintenance_page/html/assets/images/favicon-ec189703.svg.gz
  maintenance_page/html/assets/images/govuk-crest-2x.png
  maintenance_page/html/assets/images/govuk-crest.png
  maintenance_page/html/assets/images/govuk-icon-180-e0835e78.png
  maintenance_page/html/assets/images/govuk-icon-192-7b8e00f8.png
  maintenance_page/html/assets/images/govuk-icon-512-587f7e53.png
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.br
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.gz
  maintenance_page/html/assets/images/govuk-opengraph-image-bd4c811b.png
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.gz
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.gz
  maintenance_page/html/assets/images/icon-toggle-plus-minus-257426a1.svg
  maintenance_page/html/index.html
  maintenance_page/html/javascript/govuk-frontend-5.3.1.min.js
  maintenance_page/html/stylesheets/govuk-frontend-5.3.1.min.css
  maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
  maintenance_page/manifests/maintenance/service_maintenance.yml
  maintenance_page/manifests/production/ingress_external_to_main.yml
  maintenance_page/manifests/production/ingress_external_to_maintenance.yml
  maintenance_page/manifests/production/ingress_internal_to_main.yml
  maintenance_page/manifests/production/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/production/ingress_maintenance.yml
  maintenance_page/manifests/production/ingress_temp_to_main.yml
  maintenance_page/manifests/qa/ingress_external_to_main.yml
  maintenance_page/manifests/qa/ingress_external_to_maintenance.yml
  maintenance_page/manifests/qa/ingress_internal_to_main.yml
  maintenance_page/manifests/qa/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/qa/ingress_maintenance.yml
  maintenance_page/manifests/qa/ingress_temp_to_main.yml
  maintenance_page/manifests/staging/ingress_external_to_main.yml
  maintenance_page/manifests/staging/ingress_external_to_maintenance.yml
  maintenance_page/manifests/staging/ingress_internal_to_main.yml
  maintenance_page/manifests/staging/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/staging/ingress_maintenance.yml
  maintenance_page/manifests/staging/ingress_temp_to_main.yml
  maintenance_page/nginx.conf
  maintenance_page/scripts/failback.sh
  maintenance_page/scripts/failover.sh
Labels: deploy, devops
