Repository DFE-Digital/teaching-vacancies, pull requests merged in 2025-01, with the labels that each got.

#7364 Revert "Bump activerecord-import from 1.8.1 to 2.0.0"
  Gemfile.lock
Labels: deploy

#7367 Upgrade Bundler version on Gemfile
  Gemfile.lock
Labels: deploy

#7365 ATS download use MOJ multi-select and remove dfe-multi-select
  app/assets/javascript/application.js
  app/assets/javascript/dfe-multi-select.js
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/views/publishers/vacancies/job_applications/_candidates.html.slim
  app/views/publishers/vacancies/job_applications/show.html.slim
  config/locales/forms.yml
  config/routes.rb
  package.json
  spec/system/publishers/publishers_can_reject_a_job_application_spec.rb
  spec/system/publishers/publishers_can_shortlist_a_job_application_spec.rb
  yarn.lock
Labels: deploy

#7368 Ensure flexi_working column is populated with nil if the flexi_working form value only includes html tags
  app/form_models/publishers/job_listing/about_the_role_form.rb
  spec/form_models/publishers/job_listing/about_the_role_form_spec.rb
Labels: deploy

#7294 ATS Phase 1 Target Branch
  Gemfile
  Gemfile.lock
  app/assets/javascript/application.js
  app/assets/stylesheets/application.scss
  app/controllers/publishers/vacancies/job_applications/notes_controller.rb
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/form_models/publishers/job_application/download_form.rb
  app/form_models/publishers/job_application/tag_form.rb
  app/helpers/job_applications_helper.rb
  app/models/job_application.rb
  app/views/publishers/vacancies/job_applications/_application_details_and_notes.html.slim
  app/views/publishers/vacancies/job_applications/_candidates.html.slim
  app/views/publishers/vacancies/job_applications/_header.html.slim
  app/views/publishers/vacancies/job_applications/index.html.slim
  app/views/publishers/vacancies/job_applications/notes/index.html.slim
  app/views/publishers/vacancies/job_applications/show.html.slim
  app/views/publishers/vacancies/job_applications/tag.html.slim
  config/analytics.yml
  config/locales/activerecord.yml
  config/locales/forms.yml
  config/locales/publishers.yml
  config/routes.rb
  db/migrate/20241113141402_add_interviewing_at_to_job_application.rb
  db/schema.rb
  package.json
  spec/factories/job_applications.rb
  spec/helpers/job_applications_helper_spec.rb
  spec/system/publishers/job_applications_draft_spec.rb
  spec/system/publishers/publishers_can_add_notes_to_a_job_application_spec.rb
  spec/system/publishers/publishers_can_manage_job_applications_for_a_vacancy_spec.rb
  spec/system/publishers/publishers_can_reject_a_job_application_spec.rb
  spec/system/publishers/publishers_can_shortlist_a_job_application_spec.rb
  spec/system/publishers/publishers_can_view_a_job_application_spec.rb
  yarn.lock
Labels: deploy

#7048 Withdraw draft applications for expired jobs
  app/jobs/delete_old_draft_applications_for_expired_vacancies_job.rb
  config/schedule.yml
  spec/jobs/delete_old_draft_applications_for_expired_vacancies_job_spec.rb
Labels: deploy

#7376 Adding (opens in new tab) in link text
  config/locales/publishers.yml
Labels: deploy

#7353 Enable federated auth for big query
  .github/actions/deploy/action.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/delete_review_app.yml
  config/initializers/dfe_analytics.rb
  terraform/app/.terraform.lock.hcl
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/dfe_analytics.tf
  terraform/app/modules/paas/variables.tf
  terraform/app/terraform.tf
  terraform/app/variables.tf
  terraform/workspace-variables/production.tfvars.json
  terraform/workspace-variables/review.tfvars.json
  terraform/workspace-variables/staging.tfvars.json
Labels: deploy, devops

#7371 References content update
  app/controllers/jobseekers/job_applications/references_controller.rb
  app/form_models/jobseekers/job_application/details/reference_form.rb
  app/helpers/pdf_helper.rb
  app/views/jobseekers/job_applications/build/references.html.slim
  app/views/jobseekers/job_applications/references/_fields.html.slim
  app/views/jobseekers/job_applications/references/edit.html.slim
  app/views/jobseekers/job_applications/references/new.html.slim
  app/views/jobseekers/job_applications/review/_references.html.slim
  app/views/pages/job-application-preview.html.slim
  config/analytics.yml
  config/locales/activerecord.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  db/migrate/20250107110428_add_is_most_recent_employer_to_references.rb
  db/schema.rb
  spec/form_models/jobseekers/job_application/details/reference_form_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers/jobseekers_can_add_references_to_their_job_application_spec.rb
Labels: deploy

#7389 Convert to 2D Cartesian Geometry for job searches
  .devcontainer/Dockerfile
  .github/workflows/test.yml
  Dockerfile
  app/models/subscription.rb
  spec/models/subscription_spec.rb
Labels: deploy

#7390 Enable federated auth for big query for staging
  terraform/workspace-variables/staging.tfvars.json
Labels: deploy, devops

#7381 Add course length to training and CPD section of profile and job applciation
  app/controllers/jobseekers/job_applications/training_and_cpds_controller.rb
  app/controllers/jobseekers/profiles/training_and_cpds_controller.rb
  app/form_models/jobseekers/training_and_cpd_form.rb
  app/helpers/pdf_helper.rb
  app/views/jobseekers/job_applications/build/training_and_cpds.html.slim
  app/views/jobseekers/job_applications/review/_training_and_cpds.html.slim
  app/views/jobseekers/job_applications/training_and_cpds/edit.html.slim
  app/views/jobseekers/job_applications/training_and_cpds/new.html.slim
  app/views/jobseekers/profiles/qualifications/confirm_destroy.html.slim
  app/views/jobseekers/profiles/training_and_cpds/confirm_destroy.html.slim
  app/views/jobseekers/profiles/training_and_cpds/edit.html.slim
  app/views/jobseekers/profiles/training_and_cpds/new.html.slim
  app/views/jobseekers/training_and_cpds/_training_and_cpds.html.slim
  config/analytics.yml
  config/locales/activerecord.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  db/migrate/20250108105814_add_course_length_to_training_and_cpds.rb
  db/schema.rb
  spec/factories/training_and_cpds.rb
  spec/form_models/jobseekers/training_and_cpd_form_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers/jobseeker_can_add_training_and_cpds_to_their_job_application_spec.rb
  spec/system/jobseekers/jobseekers_can_add_training_to_their_profile_spec.rb
Labels: deploy

#7352 Add Awarding Body to qualification result
  app/controllers/concerns/jobseekers/qualification_form_concerns.rb
  app/controllers/jobseekers/job_applications/qualifications_controller.rb
  app/controllers/jobseekers/profiles/qualifications_controller.rb
  app/form_models/jobseekers/qualifications/qualification_form.rb
  app/form_models/jobseekers/qualifications/secondary/common_form.rb
  app/form_models/jobseekers/qualifications/secondary/qualification_result_form.rb
  app/helpers/pdf_helper.rb
  app/helpers/qualifications_helper.rb
  app/models/qualification_result.rb
  app/views/jobseekers/job_applications/build/qualifications.html.slim
  app/views/jobseekers/job_applications/qualifications/edit.html.slim
  app/views/jobseekers/job_applications/qualifications/new.html.slim
  app/views/jobseekers/job_applications/qualifications/select_category.html.slim
  app/views/jobseekers/job_applications/review/qualifications/_secondary_qualification.html.slim
  app/views/jobseekers/profiles/qualifications/confirm_destroy.html.slim
  app/views/jobseekers/profiles/qualifications/edit.html.slim
  app/views/jobseekers/profiles/qualifications/new.html.slim
  app/views/jobseekers/profiles/qualifications/select_category.html.slim
  app/views/jobseekers/qualifications/_fields.html.slim
  app/views/jobseekers/qualifications/_qualifications.html.slim
  app/views/jobseekers/qualifications/fields/_secondary_school.html.slim
  app/views/jobseekers/qualifications/review/_secondary_qualification.html.slim
  config/analytics.yml
  config/locales/forms.yml
  db/migrate/20250113144018_add_awarding_body_to_qualification_result.rb
  db/schema.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers/jobseekers_can_add_qualifications_to_their_job_application_spec.rb
Labels: deploy

#7411 Disable federated auth for big query in staging
  terraform/workspace-variables/staging.tfvars.json
Labels: devops

#7401 Induction question changes
  app/controllers/jobseekers/profiles/qualified_teacher_status_controller.rb
  app/form_models/jobseekers/job_application/professional_status_form.rb
  app/form_models/jobseekers/profile/qualified_teacher_status_form.rb
  app/helpers/pdf_helper.rb
  app/views/jobseekers/job_applications/build/professional_status.html.slim
  app/views/jobseekers/job_applications/review/_professional_status.html.slim
  app/views/jobseekers/profiles/qualified_teacher_status/_summary.html.slim
  app/views/jobseekers/profiles/qualified_teacher_status/edit.html.slim
  config/analytics.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  db/migrate/20250110135902_add_statutory_induction_complete_details_to_jobseeker_profiles.rb
  db/migrate/20250110151035_add_statutory_induction_complete_details_to_job_applications.rb
  db/schema.rb
  lib/tasks/update_statutory_induction.rake
  spec/form_models/jobseekers/job_application/professional_status_form_spec.rb
  spec/form_models/jobseekers/profile/qualified_teacher_status_form_spec.rb
  spec/system/jobseekers/jobseekers_can_add_professional_status_to_their_job_application_spec.rb
  spec/system/jobseekers/jobseekers_can_add_professional_status_to_their_profile_spec.rb
  spec/system/jobseekers/jobseekers_can_manage_a_profile_spec.rb
Labels: deploy

#7407 Remove Analytics scope from Google Api Client
  config/initializers/google_api.rb
Labels: deploy

#7422 Set option for faster geography evaluation
  app/models/organisation.rb
  app/queries/location_query.rb
  config/brakeman.ignore
  spec/queries/vacancy_location_query_spec.rb
Labels: deploy

#7430 Increase production DB resources
  documentation/alert-runbook.md
  terraform/workspace-variables/production.tfvars.json
Labels: do not merge

#7434 Fix apply button text
  app/views/vacancies/listing/_job_details.html.slim
Labels: bug, deploy

#7417 Remove other secondary qualifications
  app/controllers/jobseekers/job_applications/qualifications_controller.rb
  app/controllers/jobseekers/profiles/qualifications_controller.rb
  app/form_models/jobseekers/qualifications/other_form.rb
  app/form_models/jobseekers/qualifications/qualification_form.rb
  app/helpers/pdf_helper.rb
  app/models/qualification.rb
  app/services/qualifications_migration.rb
  app/views/jobseekers/job_applications/build/qualifications.html.slim
  app/views/jobseekers/job_applications/qualifications/new.html.slim
  app/views/jobseekers/job_applications/review/qualifications/_qualification.html.slim
  app/views/jobseekers/profiles/qualifications/new.html.slim
  app/views/jobseekers/qualifications/_qualifications.html.slim
  app/views/jobseekers/qualifications/fields/_other.html.slim
  app/views/shared/_category_fieldset.html.slim
  config/analytics.yml
  config/locales/forms.yml
  config/locales/jobseekers.yml
  db/migrate/20250115153941_add_awarding_body_to_qualification.rb
  db/schema.rb
  lib/tasks/update_other_secondary_qualifications.rake
  spec/form_models/jobseekers/qualifications/other_form_spec.rb
  spec/services/qualifications_migration_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers/jobseekers_can_add_qualifications_to_their_job_application_spec.rb
  spec/system/jobseekers/jobseekers_can_add_qualifications_to_their_profile_spec.rb
Labels: deploy

#7410 add working patterns test - job share should be or'ed with WP, not and'ed
  app/models/subscription.rb
  app/queries/vacancy_filter_query.rb
  db/seeds.rb
  spec/factories/vacancies.rb
  spec/models/subscription_spec.rb
  spec/queries/vacancy_filter_query_spec.rb
  spec/services/search/vacancy_search_spec.rb
Labels: deploy

#7423 personal statement content tweaks
  app/views/jobseekers/job_applications/build/personal_statement.html.slim
  config/locales/jobseekers.yml
Labels: deploy

#7439 Add Professional body memberships to profile
  app/controllers/jobseekers/profiles/professional_body_memberships_controller.rb
  app/controllers/jobseekers/profiles_controller.rb
  app/form_models/jobseekers/professional_body_membership_form.rb
  app/models/jobseeker_profile.rb
  app/models/professional_body_membership.rb
  app/views/jobseekers/professional_body_memberships/_professional_body_memberships.html.slim
  app/views/jobseekers/profiles/professional_body_memberships/_summary.html.slim
  app/views/jobseekers/profiles/professional_body_memberships/confirm_destroy.html.slim
  app/views/jobseekers/profiles/professional_body_memberships/edit.html.slim
  app/views/jobseekers/profiles/professional_body_memberships/new.html.slim
  app/views/jobseekers/profiles/professional_body_memberships/review.html.slim
  config/analytics.yml
  config/locales/forms.yml
  config/locales/jobseekers/professional_body_membership_form.yml
  config/routes.rb
  db/migrate/20250117112840_create_professional_body_membership.rb
  db/schema.rb
  spec/factories/professional_body_memberships.rb
  spec/form_models/jobseekers/professional_body_membership_form_spec.rb
  spec/system/jobseekers/jobseekers_can_add_professional_body_memberships_to_their_profile_spec.rb
Labels: deploy

#7440 Remove references to 'other_secondary' qualifications
  app/controllers/concerns/jobseekers/qualification_form_concerns.rb
  app/form_models/jobseekers/qualifications/secondary/other_form.rb
  app/helpers/qualifications_helper.rb
  app/models/qualification.rb
  app/services/qualifications_migration.rb
  app/views/jobseekers/qualifications/_fields.html.slim
  app/views/jobseekers/qualifications/fields/_secondary_school.html.slim
  config/locales/forms.yml
  config/locales/jobseekers.yml
  lib/tasks/update_other_secondary_qualifications.rake
  spec/factories/qualifications.rb
  spec/form_models/jobseekers/qualifications/secondary/other_form_spec.rb
  spec/models/qualification_spec.rb
  spec/services/qualifications_migration_spec.rb
  spec/support/jobseeker_helpers.rb
  spec/system/jobseekers/jobseekers_can_add_qualifications_to_their_job_application_spec.rb
  spec/system/jobseekers/jobseekers_can_add_qualifications_to_their_profile_spec.rb
Labels: deploy

#7418 Precompute Centroid for polygon areas
  app/services/ons_data_import/base.rb
  app/services/ons_data_import/create_composites.rb
  config/analytics.yml
  config/brakeman.ignore
  db/migrate/20250114180542_add_centroid_to_location_polygons.rb
  db/schema.rb
  lib/tasks/backfill_location_polygons_centroid.rake
  spec/factories/location_polygons.rb
  spec/tasks/backfill_location_polygons_centroid_spec.rb
Labels: deploy

#7444 Use stored centroids to calculate distances
  app/queries/location_query.rb
  config/brakeman.ignore
Labels: deploy

#7452 upgrade noticed gem
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
  app/models/notification.rb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/analytics_hidden_pii.yml
  db/migrate/20250129103408_remove_phantom_notification_table.rb
  db/schema.rb
Labels: deploy

#7450 tweak footer layouts
  app/views/layouts/_footer.html.slim
Labels: deploy
