Repository DFE-Digital/teaching-vacancies, pull requests merged in 2025-04, with the labels that each got.

#7660 Remove Ark and United learning
  .env.development
  .env.test
  app/jobs/import_from_vacancy_sources_job.rb
  app/services/vacancies/import/sources/ark.rb
  app/services/vacancies/import/sources/united_learning.rb
  documentation/service/integrations/integrations.md
  spec/fixtures/files/vacancy_sources/ark.xml
  spec/fixtures/files/vacancy_sources/ark_without_visa_sponsorship_available.xml
  spec/fixtures/files/vacancy_sources/united_learning.xml
  spec/fixtures/files/vacancy_sources/united_learning_argument_error.xml
  spec/fixtures/files/vacancy_sources/united_learning_with_parental_leave_cover.xml
  spec/fixtures/files/vacancy_sources/united_learning_without_visa_sponsorship_available.xml
  spec/services/vacancies/import/sources/ark_spec.rb
  spec/services/vacancies/import/sources/united_learning_spec.rb
Labels: deploy

#7666 Add artanddesignbespoke campaign page
  config/campaign_pages.yml
  config/locales/campaign_pages.yml
Labels: deploy

#7622 Store trn in job application
  app/controllers/jobseekers/job_applications/build_controller.rb
  app/controllers/jobseekers/job_applications_controller.rb
  app/controllers/jobseekers/profiles/qualified_teacher_status_controller.rb
  app/form_models/jobseekers/job_application/professional_status_form.rb
  app/form_models/jobseekers/profiles/qualified_teacher_status_form.rb
  app/helpers/job_applications_helper.rb
  app/helpers/pdf_helper.rb
  app/models/jobseeker_profile.rb
  app/services/jobseekers/job_applications/prefill_job_application_from_previous_application.rb
  app/views/jobseekers/base/_qts_fields.html.slim
  app/views/jobseekers/job_applications/review/_professional_status.html.slim
  config/analytics.yml
  config/locales/jobseekers/job_application/professional_status_form.yml
  spec/factories/jobseeker_profiles.rb
  spec/form_models/jobseekers/job_application/professional_status_form_spec.rb
  spec/form_models/jobseekers/profiles/qualified_teacher_status_form_spec.rb
  spec/models/jobseeker_profile_spec.rb
  spec/system/jobseekers/jobseekers_can_add_professional_status_to_their_job_application_spec.rb
  spec/system/jobseekers/jobseekers_can_add_professional_status_to_their_profile_spec.rb
Labels: deploy

#7672 Exclude ats-api from basic auth
  app/controllers/application_controller.rb
  spec/requests/basic_auth_spec.rb
Labels: deploy

#7667 Fix catholic form page when validations fail with attachment.
  app/views/jobseekers/job_applications/build/catholic.html.slim
Labels: bug, deploy

#7678 Fix: Do not attempt to format null baptism date on review
  app/views/jobseekers/job_applications/review/_catholic_religious_information.html.slim
Labels: bug

#7682 religious section never marked complete
  app/views/jobseekers/job_applications/apply.html.slim
Labels: bug, deploy

#7684 Update ATS API documentation
  spec/swagger_helper.rb
Labels: deploy

#7681 Update publishers.yml
  config/locales/publishers.yml
Labels: deploy

#7690 Update content on new feature reminder page.
  app/views/publishers/new_features/reminder.html.slim
  config/locales/publishers.yml
Labels: deploy

#7698 Relax Sentry parameter filtering
  config/initializers/sentry.rb
Labels: deploy

#7679 Validate incoming API requests using swagger schemas
  .devcontainer/post_create.sh
  Gemfile
  Gemfile.lock
  app/controllers/publishers/ats_api/v1/vacancies_controller.rb
  app/validators/json_swagger_validator.rb
  config/initializers/rswag_ui.rb
  documentation/development/setup/quick_start.md
  documentation/service/integrations/publisher-ats-api.md
  spec/factories/vacancies.rb
  spec/models/vacancy_spec.rb
  spec/requests/publishers/ats_api/v1/vacancies_spec.rb
  spec/validators/json_swagger_validator_spec.rb
Labels: deploy

#7688 Update how-to-list-non-teaching-roles.md
  app/views/content/get-help-hiring/how-to-create-job-listings-and-accept-applications/how-to-list-non-teaching-roles.md
Labels: deploy

#7686 Update creating-the-perfect-teacher-job-advert.md
  app/views/content/get-help-hiring/how-to-create-job-listings-and-accept-applications/creating-the-perfect-teacher-job-advert.md
Labels: deploy

#7697 Vacancy analytics
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/vacancies_controller.rb
  app/jobs/aggregate_vacancy_referrer_stats_job.rb
  app/jobs/track_vacancy_view_job.rb
  app/models/vacancy_analytics.rb
  app/services/vacancy_analytics_service.rb
  config/analytics_blocklist.yml
  config/schedule.yml
  db/migrate/20250325153836_create_vacancy_analytics.rb
  db/schema.rb
  documentation/service/technical/tracking-vacancy-views.md
  spec/configuration/sidekiq_scheduled_jobs_spec.rb
  spec/factories/vacancy_analytics.rb
  spec/jobs/aggregate_vacancy_referrer_stats_job_spec.rb
  spec/services/vacancy_analytics_service_spec.rb
  spec/system/jobseekers/jobseekers_can_view_a_vacancy_spec.rb
Labels: deploy

#7701 Awaiting feedback link
  app/components/dashboard_component.rb
  app/components/dashboard_component/dashboard_component.html.slim
  app/controllers/publishers/vacancies/expired_feedbacks_controller.rb
  app/helpers/vacancy_forms_helper.rb
  app/models/vacancy.rb
  app/views/publishers/vacancies/review_banners/_closed.html.slim
  config/locales/publishers.yml
  spec/models/vacancy_spec.rb
  spec/requests/publishers/vacancies/expired_feedbacks_spec.rb
Labels: deploy

#7700 No longer use a tag for the "Completed" status, instead just show text
  app/helpers/status_tag_helper.rb
  spec/helpers/status_tag_helper_spec.rb
  spec/system/jobseekers/prefilling_applications_spec.rb
Labels: deploy

#7723 Make fields optional for training and cpd
  app/form_models/jobseekers/training_and_cpd_form.rb
  config/locales/forms.yml
  spec/form_models/jobseekers/training_and_cpd_form_spec.rb
  spec/system/jobseekers/jobseeker_can_add_training_and_cpds_to_their_job_application_spec.rb
  spec/system/jobseekers/jobseekers_can_add_training_to_their_profile_spec.rb
Labels: deploy

#7718 Migrate now defunct job preferences role "other_teaching_support" to "other_support"
  lib/tasks/update_job_preferences_roles.rake
  spec/tasks/update_job_preferences_roles_spec.rb
Labels: deploy
