Repository DFE-Digital/teaching-vacancies, pull requests merged in 2025-09, with the labels that each got.

#8018 Update savings-methodology.html.slim
  app/views/pages/savings-methodology.html.slim
Labels: do not merge, deploy

#8020 Message archiving
  app/assets/stylesheets/components/messages.scss
  app/components/tabs_component.rb
  app/controllers/jobseekers/job_applications_controller.rb
  app/controllers/publishers/base_controller.rb
  app/controllers/publishers/candidate_messages_controller.rb
  app/controllers/publishers/vacancies/job_applications/messages_controller.rb
  app/controllers/publishers/vacancies/job_applications_controller.rb
  app/models/conversation.rb
  app/models/message.rb
  app/views/layouts/_publisher_secondary_nav.html.slim
  app/views/publishers/candidate_messages/index.html.slim
  app/views/publishers/vacancies/job_applications/_header.html.slim
  app/views/publishers/vacancies/job_applications/messages.html.slim
  app/views/publishers/vacancies/job_applications/show.html.slim
  config/analytics.yml
  config/locales/publishers.yml
  config/routes.rb
  db/migrate/20250822000000_add_archived_to_conversations.rb
  db/migrate/20250905144201_add_read_to_messages.rb
  db/schema.rb
  spec/system/publishers/publishers_can_send_messages_to_applicants_spec.rb
  spec/system/publishers/publishers_can_view_candidate_messages_spec.rb
Labels: deploy

#8042 straighten out pre interview table
  app/views/publishers/vacancies/job_applications/pre_interview_checks.html.slim
  config/locales/publishers.yml
  spec/system/publishers/publishers_can_select_a_job_application_for_interview_spec.rb
Labels: deploy

#8059 feat(2438): tv - AKS containers run as non root user
  Dockerfile
  terraform/app/modules/paas/aks_application.tf
  terraform/app/modules/paas/variables.tf
Labels: deploy, devops

#8050 content tweaks for tag form
  config/locales/publishers/job_application_status_form.yml
Labels: deploy

#8072 Messaging notifications and emails
  app/controllers/jobseekers/job_applications/messages_controller.rb
  app/helpers/notify_views_helper.rb
  app/jobs/send_messages_received_yesterday_job.rb
  app/mailers/jobseekers/message_mailer.rb
  app/mailers/publishers/message_notification_mailer.rb
  app/models/jobseekers/message_received_notifier.rb
  app/models/publisher_message.rb
  app/views/jobseekers/job_applications/_messages.html.slim
  app/views/jobseekers/message_mailer/message_received.text.erb
  app/views/publishers/message_notification_mailer/messages_received.text.erb
  app/views/publishers/vacancies/job_applications/messages.html.slim
  config/analytics_custom_events.yml
  config/locales/jobseekers.yml
  config/locales/mailers.yml
  config/locales/notifications.yml
  config/locales/publishers.yml
  config/schedule.yml
  db/migrate/20250919143236_add_index_to_messages.rb
  db/schema.rb
  spec/helpers/notify_views_helper_spec.rb
  spec/jobs/send_messages_received_yesterday_job_spec.rb
  spec/mailers/jobseekers/message_mailer_spec.rb
  spec/mailers/previews/publishers/message_notification_preview.rb
  spec/mailers/publishers/message_notification_mailer_spec.rb
  spec/models/jobseekers/message_received_notifier_spec.rb
  spec/requests/jobseekers/job_applications/messages_spec.rb
  spec/views/jobseekers/job_applications/_messages_spec.rb
  spec/views/publishers/vacancies/job_applications/messages_spec.rb
Labels: deploy

#8088 fixup expat version for CVE
  Dockerfile
Labels: deploy

#7949 Add job source to vacancy stats page
  Gemfile
  Gemfile.lock
  app/assets/javascript/application.js
  app/controllers/publishers/vacancies/statistics_controller.rb
  app/helpers/vacancies_helper.rb
  app/views/layouts/application.html.slim
  app/views/publishers/vacancies/statistics/show.html.slim
  config/initializers/content_security_policy.rb
  config/locales/publishers.yml
  package.json
  spec/system/publishers/publishers_can_view_vacancy_statistics_spec.rb
  yarn.lock
Labels: deploy

#8097 Upgrade Node to v24
  .devcontainer/Dockerfile
  .github/actions/prepare-app-env/action.yml
  .tool-versions
  package.json
Labels: deploy

#8092 Checkbox on not progressing candidate
  app/components/tab_panel_component.rb
  spec/system/publishers/publishers_can_change_status_of_applications_spec.rb
Labels: deploy

#8077 Add links to set job_application status date
  app/components/tab_panel_component.rb
  app/controllers/publishers/vacancies/job_applications_controller.rb
  config/locales/publishers/job_application_status_form.yml
  config/locales/publishers/vacancies/tabs.yml
  spec/components/tab_panel_component_spec.rb
  spec/page_objects/pages/application.rb
  spec/page_objects/pages/publisher/ats/feedback_page.rb
  spec/page_objects/pages/publisher/ats/job_applications_page.rb
  spec/page_objects/pages/publisher/ats/job_offer_date_page.rb
  spec/system/publishers/publishers_can_set_feedback_and_declined_date_spec.rb
Labels: deploy

#8057 Format note timestamp
  app/components/publisher_notes_on_job_application_component.html.slim
  spec/components/publisher_notes_on_job_application_component_spec.rb
Labels: deploy
