Repository DFE-Digital/teaching-vacancies, pull requests merged in 2025-03, with the labels that each got.

#7568 [2254] Upgrade Github action runners to ubuntu-latest
  .github/workflows/accessibility_tests.yml
  .github/workflows/backup_production_db.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/delete_review_app.yml
  .github/workflows/deploy_app_via_workflow_dispatch.yml
  .github/workflows/lint.yml
  .github/workflows/rebuild_docker_cache.yml
  .github/workflows/recreate-qa-database.yml
  .github/workflows/smoke-test.yml
  .github/workflows/test.yml
  .pa11yci
  db/scripts/sanitise.sql
  documentation/development/setup/legacy-setup.md
Labels: devops

#7586 Fix campaign pages error
  app/services/campaign_page.rb
  config/campaign_pages.yml
  config/locales/campaign_pages.yml
  spec/services/campaign_page_spec.rb
Labels: deploy

#7588 Fix campaign pages subjects
  config/campaign_pages.yml
  spec/configuration/campaign_pages_configuration_spec.rb
  spec/services/campaign_page_spec.rb
Labels: bug, deploy

#7587 bugfix: only blank TRN if has_teacher_reference_number is not set
  app/controllers/jobseekers/job_applications/build_controller.rb
  app/form_models/jobseekers/job_application/professional_status_form.rb
  app/models/jobseeker_profile.rb
  spec/form_models/jobseekers/job_application/professional_status_form_spec.rb
  spec/models/jobseeker_profile_spec.rb
Labels: deploy

#7593 Hide equal opportunities details on submitted application
  app/views/jobseekers/job_applications/review/_equal_opportunities.html.slim
  config/locales/jobseekers.yml
  spec/system/jobseekers/job_applications_submitted_spec.rb
Labels: deploy

#7605 upgrade alpine to 3.21 to avoid new CVEs from 11/3/2025
  Dockerfile
Labels: deploy

#7615 Usecorrect image for secondary school campaign page
  config/campaign_pages.yml
Labels: deploy

#7545 Remove middle schools
  app/controllers/concerns/publishers/wizardable.rb
  app/controllers/publishers/vacancies_controller.rb
  app/form_models/jobseekers/job_preferences_form.rb
  app/helpers/landing_pages_helper.rb
  app/helpers/organisations_helper.rb
  app/helpers/vacancy_forms_helper.rb
  app/models/school.rb
  app/models/subscription.rb
  app/models/vacancy.rb
  app/queries/vacancy_filter_query.rb
  app/services/vacancies/import/shared.rb
  app/services/vacancies/import/sources/broadbean.rb
  app/services/vacancies/import/sources/every.rb
  app/services/vacancies/import/sources/fusion.rb
  app/services/vacancies/import/sources/my_new_term.rb
  app/views/home/_landing_page_links.html.slim
  app/views/organisations/search/_results.html.slim
  app/views/vacancies/listing/_school.html.slim
  config/landing_pages.yml
  config/locales/en.yml
  config/locales/forms.yml
  config/locales/jobs.yml
  config/locales/publishers.yml
  config/search/keyword_filter_mappings.yml
  db/seeds.rb
  lib/tasks/remove_middle_school_vacancies.rake
  spec/helpers/vacancy_forms_helper_spec.rb
  spec/models/job_preferences/job_scope_spec.rb
  spec/models/subscription_spec.rb
  spec/presenters/subscription_presenter_spec.rb
  spec/queries/vacancy_filter_query_spec.rb
  spec/services/vacancies/import/shared_spec.rb
  spec/services/vacancies/import/sources/broadbean_spec.rb
  spec/services/vacancies/import/sources/every_spec.rb
  spec/services/vacancies/import/sources/fusion_spec.rb
  spec/services/vacancies/import/sources/my_new_term_spec.rb
Labels: deploy

#7628 fix alpine CVEs for 3.21
  Dockerfile
Labels: deploy

#7614 ATS API Fixes.
  app/controllers/publishers/ats_api/v1/vacancies_controller.rb
  app/form_models/publishers/job_listing/working_patterns_form.rb
  app/models/vacancy.rb
  app/services/publishers/ats_api/create_vacancy_service.rb
  app/services/publishers/ats_api/update_vacancy_service.rb
  app/views/publishers/ats_api/v1/vacancies/_show.json.jbuilder
  app/views/publishers/ats_api/v1/vacancies/index.json.jbuilder
  app/views/publishers/vacancies/build/working_patterns.html.slim
  spec/factories/vacancies.rb
  spec/form_models/publishers/job_listing/working_patterns_form_spec.rb
  spec/models/vacancy_spec.rb
  spec/requests/publishers/ats_api/v1/vacancies_spec.rb
  spec/services/publishers/ats_api/create_vacancy_service_spec.rb
  spec/services/publishers/ats_api/update_vacancy_service_spec.rb
  spec/swagger_helper.rb
Labels: deploy

#7620 Change through filter name
  config/locales/en.yml
  config/locales/forms.yml
  config/locales/jobs.yml
  config/locales/landing_pages.yml
  config/locales/publishers.yml
  spec/system/jobseekers/jobseekers_can_add_job_preferences_to_their_profile_spec.rb
Labels: deploy

#7636 Change link address
  app/views/layouts/_footer.html.slim
Labels: deploy

#7616 Various bug fixes on school page
  app/form_models/school_search_form.rb
  app/services/search/school_search.rb
  app/services/search/vacancy_search.rb
  app/services/search/wider_suggestions_builder.rb
  app/views/organisations/_organisation.html.slim
  app/views/organisations/index.html.slim
  app/views/organisations/search/_wider_search.html.slim
  config/locales/en.yml
  config/locales/organisations.yml
  spec/form_models/school_search_form_spec.rb
  spec/services/search/school_search_spec.rb
  spec/services/search/vacancy_search_spec.rb
  spec/services/search/wider_suggestions_builder_spec.rb
Labels: deploy

#7639 CES feedback updates
  app/views/jobseekers/job_applications/build/professional_body_memberships.html.slim
  app/views/publishers/vacancies/build/applying_for_the_job.html.slim
  config/locales/jobseekers.yml
  config/locales/jobseekers/professional_body_membership_form.yml
  config/locales/publishers/applying_for_the_job.yml
Labels: deploy

#7584 Jobseekers emails optout
  app/controllers/jobseekers/email_preferences_controller.rb
  app/models/feedback.rb
  app/models/jobseeker.rb
  app/views/jobseekers/accounts/show.html.slim
  app/views/jobseekers/email_preferences/edit.html.slim
  config/analytics.yml
  config/locales/jobseekers.yml
  config/locales/jobseekers/email_preferences_form.yml
  config/routes.rb
  db/migrate/20250304103139_add_email_preferences_to_jobseekers.rb
  db/schema.rb
  spec/models/jobseeker_spec.rb
  spec/system/jobseekers/jobseekers_can_give_account_feedback_spec.rb
Labels: deploy

#7644 [ATS API] Soft delete vacancies
  app/controllers/publishers/ats_api/v1/vacancies_controller.rb
  app/controllers/publishers/vacancies/base_controller.rb
  app/controllers/publishers/vacancies_controller.rb
  app/models/vacancy.rb
  spec/controllers/publishers/vacancies/base_controller_spec.rb
  spec/models/vacancy_spec.rb
  spec/requests/publishers/ats_api/v1/vacancies_spec.rb
  spec/system/publishers/publishers_can_delete_vacancies_spec.rb
Labels: deploy

#7643 API vacancy validations
  app/validators/external_vacancy_validator.rb
  spec/fixtures/files/vacancy_sources/broadband_not_parental_leave_cover.xml
  spec/fixtures/files/vacancy_sources/broadbean.xml
  spec/fixtures/files/vacancy_sources/broadbean_without_schools.xml
  spec/fixtures/files/vacancy_sources/broadbean_without_trust.xml
  spec/fixtures/files/vacancy_sources/broadbean_without_visa_sponsorship_available.xml
  spec/fixtures/files/vacancy_sources/every.json
  spec/fixtures/files/vacancy_sources/every_without_trust.json
  spec/fixtures/files/vacancy_sources/fusion.json
  spec/fixtures/files/vacancy_sources/fusion_argument_error.json
  spec/fixtures/files/vacancy_sources/my_new_term.json
  spec/fixtures/files/vacancy_sources/united_learning.xml
  spec/fixtures/files/vacancy_sources/united_learning_argument_error.xml
  spec/fixtures/files/vacancy_sources/united_learning_with_parental_leave_cover.xml
  spec/fixtures/files/vacancy_sources/united_learning_without_visa_sponsorship_available.xml
  spec/fixtures/files/vacancy_sources/vacancy_poster.xml
  spec/fixtures/files/vacancy_sources/ventrus.xml
  spec/fixtures/files/vacancy_sources/ventrus_with_parental_leave_cover.xml
  spec/fixtures/files/vacancy_sources/ventrus_without_visa_sponsorship_available.xml
  spec/jobs/import_from_vacancy_source_job_spec.rb
  spec/models/vacancy_spec.rb
  spec/requests/publishers/ats_api/v1/vacancies_spec.rb
  spec/services/publishers/ats_api/create_vacancy_service_spec.rb
  spec/services/publishers/ats_api/update_vacancy_service_spec.rb
  spec/services/vacancies/import/sources/every_spec.rb
  spec/services/vacancies/import/sources/fusion_spec.rb
  spec/services/vacancies/import/sources/my_new_term_spec.rb
  spec/services/vacancies/import/sources/united_learning_spec.rb
  spec/validators/external_vacancy_validator_spec.rb
Labels: deploy

#7649 Make publisher ATS API easier to test
  .env.development
  db/seeds.rb
  documentation/service/integrations/publisher-ats-api.md
  spec/swagger_helper.rb
Labels: deploy

#7655 Fix org fetching exception
  app/controllers/publishers/organisations_controller.rb
  spec/requests/publishers/organisations/profile_listing_spec.rb
Labels: deploy

#7650 Delete subscription when email invalid
  app/mailers/jobseekers/alert_mailer.rb
  spec/mailers/jobseekers/alert_mailer_spec.rb
Labels: deploy

#7658 Fix typo
  config/locales/jobseekers.yml
Labels: deploy

#7656 Send peak times reminder email
  app/controllers/jobseekers/govuk_one_login_callbacks_controller.rb
  app/jobs/send_peak_times_email_reminder_job.rb
  app/mailers/jobseekers/peak_times_mailer.rb
  app/models/jobseeker.rb
  app/views/jobseekers/peak_times_mailer/reminder.text.erb
  config/analytics_custom_events.yml
  config/locales/mailers.yml
  config/schedule.yml
  spec/factories/jobseekers.rb
  spec/jobs/send_peak_times_email_reminder_job_spec.rb
  spec/mailers/jobseekers/peak_times_mailer_spec.rb
  spec/mailers/previews/jobseekers/peak_times_preview.rb
  spec/models/jobseeker_spec.rb
  spec/requests/jobseekers/govuk_one_login_spec.rb
Labels: deploy
